# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

def parseQuantity(expression: str, /) -> Quantity: ...
def getSchema() -> int: ...
def setSchema(index: int, /) -> None: ...
def schemaTranslate(quantity: Quantity, schema: int, /) -> tuple[str, float, str]: ...
