# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

import FreeCAD as App
from collections.abc import Sequence
from enum import IntEnum
from typing import ClassVar, Protocol, TypeAlias

from FreeCAD import DocumentObject

_Pathish: TypeAlias = str | bytes | bytearray
_IconContent: TypeAlias = str | bytes | bytearray | memoryview
_WorkbenchMenu: TypeAlias = str | Sequence[str]
_WorkbenchCommands: TypeAlias = str | Sequence[str]

class UserInput(IntEnum):
    ModifierShift = ...
    ModifierCtrl = ...
    ModifierAlt = ...
    ModifierMeta = ...
    KeySpace = ...
    KeyExclam = ...
    KeyQuoteDbl = ...
    KeyNumberSign = ...
    KeyDollar = ...
    KeyPercent = ...
    KeyAmpersand = ...
    KeyApostrophe = ...
    KeyParenLeft = ...
    KeyParenRight = ...
    KeyAsterisk = ...
    KeyPlus = ...
    KeyComma = ...
    KeyMinus = ...
    KeyPeriod = ...
    KeySlash = ...
    Key0 = ...
    Key1 = ...
    Key2 = ...
    Key3 = ...
    Key4 = ...
    Key5 = ...
    Key6 = ...
    Key7 = ...
    Key8 = ...
    Key9 = ...
    KeyColon = ...
    KeySemicolon = ...
    KeyLess = ...
    KeyEqual = ...
    KeyGreater = ...
    KeyQuestion = ...
    KeyAt = ...
    KeyA = ...
    KeyB = ...
    KeyC = ...
    KeyD = ...
    KeyE = ...
    KeyF = ...
    KeyG = ...
    KeyH = ...
    KeyI = ...
    KeyJ = ...
    KeyK = ...
    KeyL = ...
    KeyM = ...
    KeyN = ...
    KeyO = ...
    KeyP = ...
    KeyQ = ...
    KeyR = ...
    KeyS = ...
    KeyT = ...
    KeyU = ...
    KeyV = ...
    KeyW = ...
    KeyX = ...
    KeyY = ...
    KeyZ = ...
    KeyBracketLeft = ...
    KeyBackslash = ...
    KeyBracketRight = ...
    KeyAsciiCircum = ...
    KeyUnderscore = ...
    KeyQuoteLeft = ...
    KeyBraceLeft = ...
    KeyBar = ...
    KeyBraceRight = ...
    KeyAsciiTilde = ...
    KeyEscape = ...
    KeyTab = ...
    KeyBacktab = ...
    KeyBackspace = ...
    KeyReturn = ...
    KeyEnter = ...
    KeyInsert = ...
    KeyDelete = ...
    KeyPause = ...
    KeyPrintScr = ...
    KeySysReq = ...
    KeyClear = ...
    KeyHome = ...
    KeyEnd = ...
    KeyLeft = ...
    KeyUp = ...
    KeyRight = ...
    KeyDown = ...
    KeyPageUp = ...
    KeyPageDown = ...
    KeyShift = ...
    KeyControl = ...
    KeyMeta = ...
    KeyAlt = ...
    KeyCapsLock = ...
    KeyNumLock = ...
    KeyScrollLock = ...
    KeyF1 = ...
    KeyF2 = ...
    KeyF3 = ...
    KeyF4 = ...
    KeyF5 = ...
    KeyF6 = ...
    KeyF7 = ...
    KeyF8 = ...
    KeyF9 = ...
    KeyF10 = ...
    KeyF11 = ...
    KeyF12 = ...
    KeyF13 = ...
    KeyF14 = ...
    KeyF15 = ...
    KeyF16 = ...
    KeyF17 = ...
    KeyF18 = ...
    KeyF19 = ...
    KeyF20 = ...
    KeyF21 = ...
    KeyF22 = ...
    KeyF23 = ...
    KeyF24 = ...
    KeyF25 = ...
    KeyF26 = ...
    KeyF27 = ...
    KeyF28 = ...
    KeyF29 = ...
    KeyF30 = ...
    KeyF31 = ...
    KeyF32 = ...
    KeyF33 = ...
    KeyF34 = ...
    KeyF35 = ...
    MouseMove = ...
    MouseLeft = ...
    MouseRight = ...
    MouseMiddle = ...
    MouseScroll = ...
    MouseScrollUp = ...
    MouseScrollDown = ...

_InputSequence: TypeAlias = UserInput | tuple[UserInput, ...]

class _WorkbenchBackend(Protocol):
    def appendToolbar(self, name: str, cmds: Sequence[str], /) -> None: ...
    def removeToolbar(self, name: str, /) -> None: ...
    def listToolbars(self) -> list[str]: ...
    def getToolbarItems(self) -> dict[str, list[str]]: ...
    def appendCommandbar(self, name: str, cmds: Sequence[str], /) -> None: ...
    def removeCommandbar(self, name: str, /) -> None: ...
    def listCommandbars(self) -> list[str]: ...
    def appendMenu(self, name: _WorkbenchMenu, cmds: _WorkbenchCommands, /) -> None: ...
    def removeMenu(self, name: _WorkbenchMenu, /) -> None: ...
    def listMenus(self) -> list[str]: ...
    def appendContextMenu(self, name: str, cmds: _WorkbenchCommands, /) -> None: ...
    def removeContextMenu(self, name: str, /) -> None: ...
    def reloadActive(self) -> None: ...
    def name(self) -> str: ...

class Workbench:
    MenuText: ClassVar[str]
    ToolTip: ClassVar[str]
    Icon: ClassVar[object | None]
    __Workbench__: _WorkbenchBackend

    def Initialize(self) -> None: ...
    def ContextMenu(self, recipient: object, /) -> None: ...
    def appendToolbar(self, name: str, cmds: Sequence[str], /) -> None: ...
    def removeToolbar(self, name: str, /) -> None: ...
    def listToolbars(self) -> list[str]: ...
    def getToolbarItems(self) -> dict[str, list[str]]: ...
    def appendCommandbar(self, name: str, cmds: Sequence[str], /) -> None: ...
    def removeCommandbar(self, name: str, /) -> None: ...
    def listCommandbars(self) -> list[str]: ...
    def appendMenu(self, name: _WorkbenchMenu, cmds: _WorkbenchCommands, /) -> None: ...
    def removeMenu(self, name: _WorkbenchMenu, /) -> None: ...
    def listMenus(self) -> list[str]: ...
    def appendContextMenu(self, name: str, cmds: _WorkbenchCommands, /) -> None: ...
    def removeContextMenu(self, name: str, /) -> None: ...
    def reloadActive(self) -> None: ...
    def name(self) -> str: ...
    def GetClassName(self) -> str: ...

class InputHint:
    InputSequence: ClassVar[object]
    message: str
    sequences: list[_InputSequence]

    def __init__(self, message: str, *sequences: _InputSequence) -> None: ...

class _HintManager:
    def show(self, *hints: InputHint) -> None: ...
    def hide(self) -> None: ...

def listCommands() -> list[str]: ...
def isCommandActive(name: str, /) -> bool: ...

HintManager: _HintManager
ActiveDocument: Document | None
