# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

import FreeCAD as App
from collections.abc import Sequence
from enum import IntEnum
from typing import ClassVar, Literal, Protocol, TypeAlias, overload

from FreeCAD import DocumentObject

_Pathish: TypeAlias = str | bytes | bytearray
_IconContent: TypeAlias = str | bytes | bytearray | memoryview
_WorkbenchMenu: TypeAlias = str | Sequence[str]
_WorkbenchCommands: TypeAlias = str | Sequence[str]

class UserInput(IntEnum):
    ModifierShift = ...
    ModifierCtrl = ...
    ModifierAlt = ...
    ModifierMeta = ...
    KeySpace = ...
    KeyExclam = ...
    KeyQuoteDbl = ...
    KeyNumberSign = ...
    KeyDollar = ...
    KeyPercent = ...
    KeyAmpersand = ...
    KeyApostrophe = ...
    KeyParenLeft = ...
    KeyParenRight = ...
    KeyAsterisk = ...
    KeyPlus = ...
    KeyComma = ...
    KeyMinus = ...
    KeyPeriod = ...
    KeySlash = ...
    Key0 = ...
    Key1 = ...
    Key2 = ...
    Key3 = ...
    Key4 = ...
    Key5 = ...
    Key6 = ...
    Key7 = ...
    Key8 = ...
    Key9 = ...
    KeyColon = ...
    KeySemicolon = ...
    KeyLess = ...
    KeyEqual = ...
    KeyGreater = ...
    KeyQuestion = ...
    KeyAt = ...
    KeyA = ...
    KeyB = ...
    KeyC = ...
    KeyD = ...
    KeyE = ...
    KeyF = ...
    KeyG = ...
    KeyH = ...
    KeyI = ...
    KeyJ = ...
    KeyK = ...
    KeyL = ...
    KeyM = ...
    KeyN = ...
    KeyO = ...
    KeyP = ...
    KeyQ = ...
    KeyR = ...
    KeyS = ...
    KeyT = ...
    KeyU = ...
    KeyV = ...
    KeyW = ...
    KeyX = ...
    KeyY = ...
    KeyZ = ...
    KeyBracketLeft = ...
    KeyBackslash = ...
    KeyBracketRight = ...
    KeyAsciiCircum = ...
    KeyUnderscore = ...
    KeyQuoteLeft = ...
    KeyBraceLeft = ...
    KeyBar = ...
    KeyBraceRight = ...
    KeyAsciiTilde = ...
    KeyEscape = ...
    KeyTab = ...
    KeyBacktab = ...
    KeyBackspace = ...
    KeyReturn = ...
    KeyEnter = ...
    KeyInsert = ...
    KeyDelete = ...
    KeyPause = ...
    KeyPrintScr = ...
    KeySysReq = ...
    KeyClear = ...
    KeyHome = ...
    KeyEnd = ...
    KeyLeft = ...
    KeyUp = ...
    KeyRight = ...
    KeyDown = ...
    KeyPageUp = ...
    KeyPageDown = ...
    KeyShift = ...
    KeyControl = ...
    KeyMeta = ...
    KeyAlt = ...
    KeyCapsLock = ...
    KeyNumLock = ...
    KeyScrollLock = ...
    KeyF1 = ...
    KeyF2 = ...
    KeyF3 = ...
    KeyF4 = ...
    KeyF5 = ...
    KeyF6 = ...
    KeyF7 = ...
    KeyF8 = ...
    KeyF9 = ...
    KeyF10 = ...
    KeyF11 = ...
    KeyF12 = ...
    KeyF13 = ...
    KeyF14 = ...
    KeyF15 = ...
    KeyF16 = ...
    KeyF17 = ...
    KeyF18 = ...
    KeyF19 = ...
    KeyF20 = ...
    KeyF21 = ...
    KeyF22 = ...
    KeyF23 = ...
    KeyF24 = ...
    KeyF25 = ...
    KeyF26 = ...
    KeyF27 = ...
    KeyF28 = ...
    KeyF29 = ...
    KeyF30 = ...
    KeyF31 = ...
    KeyF32 = ...
    KeyF33 = ...
    KeyF34 = ...
    KeyF35 = ...
    MouseMove = ...
    MouseLeft = ...
    MouseRight = ...
    MouseMiddle = ...
    MouseScroll = ...
    MouseScrollUp = ...
    MouseScrollDown = ...

_InputSequence: TypeAlias = UserInput | tuple[UserInput, ...]

class _WorkbenchBackend(Protocol):
    def appendToolbar(self, name: str, cmds: Sequence[str], /) -> None: ...
    def removeToolbar(self, name: str, /) -> None: ...
    def listToolbars(self) -> list[str]: ...
    def getToolbarItems(self) -> dict[str, list[str]]: ...
    def appendCommandbar(self, name: str, cmds: Sequence[str], /) -> None: ...
    def removeCommandbar(self, name: str, /) -> None: ...
    def listCommandbars(self) -> list[str]: ...
    def appendMenu(self, name: _WorkbenchMenu, cmds: _WorkbenchCommands, /) -> None: ...
    def removeMenu(self, name: _WorkbenchMenu, /) -> None: ...
    def listMenus(self) -> list[str]: ...
    def appendContextMenu(self, name: str, cmds: _WorkbenchCommands, /) -> None: ...
    def removeContextMenu(self, name: str, /) -> None: ...
    def reloadActive(self) -> None: ...
    def name(self) -> str: ...

class Workbench:
    MenuText: ClassVar[str]
    ToolTip: ClassVar[str]
    Icon: ClassVar[object | None]
    __Workbench__: _WorkbenchBackend

    def Initialize(self) -> None: ...
    def ContextMenu(self, recipient: object, /) -> None: ...
    def appendToolbar(self, name: str, cmds: Sequence[str], /) -> None: ...
    def removeToolbar(self, name: str, /) -> None: ...
    def listToolbars(self) -> list[str]: ...
    def getToolbarItems(self) -> dict[str, list[str]]: ...
    def appendCommandbar(self, name: str, cmds: Sequence[str], /) -> None: ...
    def removeCommandbar(self, name: str, /) -> None: ...
    def listCommandbars(self) -> list[str]: ...
    def appendMenu(self, name: _WorkbenchMenu, cmds: _WorkbenchCommands, /) -> None: ...
    def removeMenu(self, name: _WorkbenchMenu, /) -> None: ...
    def listMenus(self) -> list[str]: ...
    def appendContextMenu(self, name: str, cmds: _WorkbenchCommands, /) -> None: ...
    def removeContextMenu(self, name: str, /) -> None: ...
    def reloadActive(self) -> None: ...
    def name(self) -> str: ...
    def GetClassName(self) -> str: ...

class InputHint:
    InputSequence: ClassVar[object]
    message: str
    sequences: list[_InputSequence]

    def __init__(self, message: str, *sequences: _InputSequence) -> None: ...

class _HintManager:
    def show(self, *hints: InputHint) -> None: ...
    def hide(self) -> None: ...

def subgraphFromObject(obj: DocumentObject, /) -> object | None: ...
def exportSubgraph(node: object, output: object, format: str = "VRML", /) -> None: ...
def getSoDBVersion() -> str: ...
def listCommands() -> list[str]: ...
def isCommandActive(name: str, /) -> bool: ...
def activateWorkbench(name: str, /) -> bool: ...
def addWorkbench(workbench: Workbench | type[Workbench], /) -> None: ...
def removeWorkbench(name: str, /) -> None: ...
def getWorkbench(name: str, /) -> Workbench: ...
def listWorkbenches() -> dict[str, Workbench]: ...
def activeWorkbench() -> Workbench: ...
def addResourcePath(path: _Pathish, /) -> None: ...
def addLanguagePath(path: _Pathish, /) -> None: ...
def addIconPath(path: _Pathish, /) -> None: ...
def addIcon(name: str, content: _IconContent, format: str = "XPM", /) -> None: ...
def getIcon(name: str, /) -> object | None: ...
def isIconCached(name: str, /) -> bool: ...
def getMainWindow() -> _MainWindow: ...
def updateGui() -> None: ...
def updateLocale() -> None: ...
def getLocale() -> str: ...
def setLocale(name: str, /) -> None: ...
def supportedLocales() -> dict[str, str]: ...
def createDialog(path: str, /) -> _PyResource: ...
@overload
def addPreferencePage(path: str, group: str, /) -> None: ...
@overload
def addPreferencePage(dialog: type[object], group: str, /) -> None: ...
def addCommand(name: str, cmd: object, activation: str = "", /) -> None: ...
def runCommand(name: str, index: int = 0, /) -> None: ...
def SendMsgToActiveView(name: str, suppress: bool = False, /) -> None: ...
def sendMsgToFocusView(name: str, suppress: bool = False, /) -> None: ...
def hide(name: str, /) -> None: ...
def show(name: str, /) -> None: ...
def hideObject(obj: DocumentObject, /) -> None: ...
def showObject(obj: DocumentObject, /) -> None: ...
def open(fileName: _Pathish, /) -> None: ...
def insert(fileName: _Pathish, docName: str = "", /) -> None: ...
def export(objs: Sequence[DocumentObject], fileName: _Pathish, /) -> None: ...
def activeDocument() -> Document | None: ...
def setActiveDocument(doc: str | App.Document, /) -> None: ...
@overload
def activeView() -> object | None: ...
@overload
def activeView(typeName: str, /) -> object | None: ...
def activateView(typeName: str, create: bool, /) -> None: ...
def editDocument() -> Document | None: ...
def getDocument(doc: str | App.Document, /) -> Document: ...
def doCommand(cmd: str, /) -> None: ...
def doCommandGui(cmd: str, /) -> None: ...
def doCommandEval(cmd: str, /) -> object: ...
def doCommandSkip(cmd: str, /) -> None: ...
def addModule(mod: str, /) -> None: ...
def showDownloads() -> None: ...
def showPreferences(grp: str = "", index: int = 0, /) -> None: ...
def showPreferencesByName(grp: str, pagename: str = "", /) -> None: ...
@overload
def createViewer() -> _View3DInventor: ...
@overload
def createViewer(views: Literal[1], name: str = ..., /) -> _View3DInventor: ...
@overload
def createViewer(views: int, name: str = ..., /) -> _View3DInventor | _AbstractSplitView: ...
def getMarkerIndex(marker: str, size: int = 9, /) -> int: ...
def addDocumentObserver(obj: object, /) -> None: ...
def removeDocumentObserver(obj: object, /) -> None: ...
def addWorkbenchManipulator(obj: object, /) -> None: ...
def removeWorkbenchManipulator(obj: object, /) -> None: ...
def listUserEditModes() -> list[str]: ...
def getUserEditMode() -> str: ...
def setUserEditMode(mode: str, /) -> bool: ...
def reload(name: str, /) -> App.Document | None: ...
def loadFile(fileName: str, module: str = "", /) -> None: ...
def coinRemoveAllChildren(node: object, /) -> None: ...
def suspendWaitCursor() -> None: ...
def resumeWaitCursor() -> None: ...
def showMainWindow(inThread: bool = False, /) -> None: ...
def exec_loop() -> None: ...
def setupWithoutGUI() -> None: ...
def embedToWindow(pointer: str, /) -> None: ...

HintManager: _HintManager
ActiveDocument: Document | None
