# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

from typing import overload

def subgraphFromObject(obj: DocumentObject, /) -> object | None: ...
def exportSubgraph(node: object, output: object, format: str = "VRML", /) -> None: ...
def getSoDBVersion() -> str: ...
def activateWorkbench(name: str, /) -> bool: ...
def addWorkbench(workbench: Workbench | type[Workbench], /) -> None: ...
def removeWorkbench(name: str, /) -> None: ...
def getWorkbench(name: str, /) -> Workbench: ...
def listWorkbenches() -> dict[str, Workbench]: ...
def activeWorkbench() -> Workbench: ...
def addResourcePath(path: _Pathish, /) -> None: ...
def addLanguagePath(path: _Pathish, /) -> None: ...
def addIconPath(path: _Pathish, /) -> None: ...
def addIcon(name: str, content: _IconContent, format: str = "XPM", /) -> None: ...
def getIcon(name: str, /) -> object | None: ...
def isIconCached(name: str, /) -> bool: ...
def getMainWindow() -> _MainWindow: ...
def updateGui() -> None: ...
def updateLocale() -> None: ...
def getLocale() -> str: ...
def setLocale(name: str, /) -> None: ...
def supportedLocales() -> dict[str, str]: ...
def createDialog(path: str, /) -> _PyResource: ...
@overload
def addPreferencePage(path: str, group: str, /) -> None: ...
@overload
def addPreferencePage(dialog: type[object], group: str, /) -> None: ...
def addCommand(name: str, cmd: object, activation: str = "", /) -> None: ...
def runCommand(name: str, index: int = 0, /) -> None: ...
def SendMsgToActiveView(name: str, suppress: bool = False, /) -> None: ...
def sendMsgToFocusView(name: str, suppress: bool = False, /) -> None: ...
def hide(name: str, /) -> None: ...
def show(name: str, /) -> None: ...
def hideObject(obj: DocumentObject, /) -> None: ...
def showObject(obj: DocumentObject, /) -> None: ...
def open(fileName: _Pathish, /) -> None: ...
def insert(fileName: _Pathish, docName: str = "", /) -> None: ...
def export(objs: Sequence[DocumentObject], fileName: _Pathish, /) -> None: ...
def activeDocument() -> Document | None: ...
def setActiveDocument(doc: str | App.Document, /) -> None: ...
@overload
def activeView() -> object | None: ...
@overload
def activeView(typeName: str, /) -> object | None: ...
def activateView(typeName: str, create: bool, /) -> None: ...
def editDocument() -> Document | None: ...
def getDocument(doc: str | App.Document, /) -> Document: ...
def doCommand(cmd: str, /) -> None: ...
def doCommandGui(cmd: str, /) -> None: ...
def doCommandEval(cmd: str, /) -> object: ...
def doCommandSkip(cmd: str, /) -> None: ...
def addModule(mod: str, /) -> None: ...
def showDownloads() -> None: ...
def showPreferences(grp: str = "", index: int = 0, /) -> None: ...
def showPreferencesByName(grp: str, pagename: str = "", /) -> None: ...
@overload
def createViewer() -> _View3DInventor: ...
@overload
def createViewer(views: Literal[1], name: str = ..., /) -> _View3DInventor: ...
@overload
def createViewer(views: int, name: str = ..., /) -> _View3DInventor | _AbstractSplitView: ...
def getMarkerIndex(marker: str, size: int = 9, /) -> int: ...
def addDocumentObserver(obj: object, /) -> None: ...
def removeDocumentObserver(obj: object, /) -> None: ...
def addWorkbenchManipulator(obj: object, /) -> None: ...
def removeWorkbenchManipulator(obj: object, /) -> None: ...
def listUserEditModes() -> list[str]: ...
def getUserEditMode() -> str: ...
def setUserEditMode(mode: str, /) -> bool: ...
def reload(name: str, /) -> App.Document | None: ...
def loadFile(fileName: str, module: str = "", /) -> None: ...
def coinRemoveAllChildren(node: object, /) -> None: ...
def suspendWaitCursor() -> None: ...
def resumeWaitCursor() -> None: ...
def showMainWindow(inThread: bool = False, /) -> None: ...
def exec_loop() -> None: ...
def setupWithoutGUI() -> None: ...
def embedToWindow(pointer: str, /) -> None: ...
