# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

class _AbstractSplitView:
    def fitAll(self, factor: float = 1.0, /) -> None: ...
    def viewBottom(self) -> None: ...
    def viewFront(self) -> None: ...
    def viewLeft(self) -> None: ...
    def viewRear(self) -> None: ...
    def viewRight(self) -> None: ...
    def viewTop(self) -> None: ...
    def viewAxometric(self) -> None: ...
    def viewIsometric(self) -> None: ...
    def getViewer(self, index: int, /) -> object: ...
    def close(self) -> None: ...
    def cast_to_base(self) -> object: ...
