# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

class _Control:
    def showDialog(self, dialog: object, document: object | None = None, /) -> object: ...
    def activeDialog(self, document: object | None = None, /) -> bool: ...
    def activeTaskDialog(self, document: object | None = None, /) -> object | None: ...
    def closeDialog(self, document: object | None = None, /) -> None: ...
    def addTaskWatcher(self, watchers: object, /) -> None: ...
    def clearTaskWatcher(self) -> None: ...
    def isAllowedAlterDocument(self, document: object | None = None, /) -> bool: ...
    def isAllowedAlterView(self, document: object | None = None, /) -> bool: ...
    def isAllowedAlterSelection(self, document: object | None = None, /) -> bool: ...
    def showTaskView(self) -> None: ...
    def showModelView(self) -> None: ...
