# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

class _MainWindow:
    def getWindows(self) -> list[object]: ...
    def getWindowsOfType(self, type_id: object, /) -> list[object]: ...
    def setActiveWindow(self, view: object, /) -> None: ...
    def getActiveWindow(self) -> object | None: ...
    def addWindow(self, window: object, /) -> object | None: ...
    def removeWindow(self, view: object, /) -> None: ...
    def showHint(self, *hints: object) -> None: ...
    def hideHint(self) -> None: ...
