# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

class _MDIView:
    def printView(self) -> None: ...
    def printPdf(self) -> None: ...
    def printPreview(self) -> None: ...
    def undoActions(self) -> list[str]: ...
    def redoActions(self) -> list[str]: ...
    def message(self, message: str, /) -> bool: ...
    def sendMessage(self, message: str, /) -> bool: ...
    def supportMessage(self, message: str, /) -> bool: ...
    def fitAll(self) -> None: ...
    def setActiveObject(
        self, name: str, document_object: object | None = None, subname: str | None = None, /
    ) -> None: ...
    def getActiveObject(self, name: str, resolve: bool = True, /) -> object: ...
    def cast_to_base(self) -> object: ...
