# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

class _PyResource:
    def value(
        self, object_name: str, property_name: str, /
    ) -> str | int | float | bool | list[str] | None: ...
    def setValue(self, object_name: str, property_name: str, value: object, /) -> None: ...
    def show(self) -> None: ...
    def connect(self, sender: str, signal: str, callback: object, /) -> None: ...
