# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

from typing import Any

class _TaskDialog:
    def getDialogContent(self) -> list[Any]: ...
    def getStandardButtons(self) -> int: ...
    def setEscapeButtonEnabled(self, enabled: bool, /) -> None: ...
    def isEscapeButtonEnabled(self) -> bool: ...
    def setAutoCloseOnTransactionChange(self, enabled: bool, /) -> None: ...
    def isAutoCloseOnTransactionChange(self) -> bool: ...
    def setAutoCloseOnDeletedDocument(self, enabled: bool, /) -> None: ...
    def isAutoCloseOnDeletedDocument(self) -> bool: ...
    def getDocumentName(self) -> str: ...
    def setDocumentName(self, name: str, /) -> None: ...
    def isAllowedAlterDocument(self) -> bool: ...
    def isAllowedAlterView(self) -> bool: ...
    def isAllowedAlterSelection(self) -> bool: ...
    def needsFullSpace(self) -> bool: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...
