# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

from typing import Any

class _View3DInventorViewer:
    def getSoRenderManager(self) -> Any: ...
    def getSoEventManager(self) -> Any: ...
    def getSceneGraph(self) -> Any: ...
    def setSceneGraph(self, node: object, /) -> None: ...
    def seekToPoint(self, point: object, /) -> None: ...
    def setFocalDistance(self, distance: float, /) -> None: ...
    def getFocalDistance(self) -> float: ...
    def getPoint(self, x: int, y: int, /) -> Any: ...
    def getPointOnFocalPlane(self, x: int, y: int, /) -> Any: ...
    def getPickRadius(self) -> float: ...
    def setPickRadius(self, radius: float, /) -> None: ...
    def setupEditingRoot(
        self, node: object | None = None, matrix: object | None = None, /
    ) -> None: ...
    def resetEditingRoot(self, update_links: bool = True, /) -> None: ...
    def setBackgroundColor(self, red: float, green: float, blue: float, /) -> None: ...
    def setGradientBackground(self, background: str, /) -> None: ...
    def setGradientBackgroundColor(
        self,
        from_color: tuple[float, float, float],
        to_color: tuple[float, float, float],
        mid_color: tuple[float, float, float] | None = None,
        /,
    ) -> None: ...
    def setRedirectToSceneGraph(self, redirect: bool, /) -> None: ...
    def isRedirectedToSceneGraph(self) -> bool: ...
    def grabFramebuffer(self) -> Any: ...
    def setOverrideMode(self, mode: str, /) -> None: ...
    def setEnabledNaviCube(self, enabled: bool, /) -> None: ...
    def isEnabledNaviCube(self) -> bool: ...
    def setNaviCubeCorner(self, corner: int, /) -> None: ...
    def getNavigationStyle(self) -> object | None: ...
