# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

from typing import Any

class _View3DInventor:
    def fitAll(self, factor: float = 1.0, /) -> None: ...
    def boxZoom(self, XMin: int, YMin: int, XMax: int, YMax: int) -> None: ...
    def viewBottom(self) -> None: ...
    def viewFront(self) -> None: ...
    def viewLeft(self) -> None: ...
    def viewRear(self) -> None: ...
    def viewRight(self) -> None: ...
    def viewTop(self) -> None: ...
    def viewAxometric(self) -> None: ...
    def viewAxonometric(self) -> None: ...
    def viewIsometric(self) -> None: ...
    def viewDimetric(self) -> None: ...
    def viewTrimetric(self) -> None: ...
    def viewDefaultOrientation(self, view: str | None = None, scale: float = -1.0, /) -> None: ...
    def viewRotateLeft(self) -> None: ...
    def viewRotateRight(self) -> None: ...
    def zoomIn(self) -> None: ...
    def zoomOut(self) -> None: ...
    def viewPosition(
        self, placement: object | None = None, steps: int = 0, duration: int = -1, /
    ) -> object | None: ...
    def startAnimating(self, x: float, y: float, z: float, velocity: float, /) -> None: ...
    def stopAnimating(self) -> None: ...
    def setAnimationEnabled(self, enabled: bool, /) -> None: ...
    def isAnimationEnabled(self) -> bool: ...
    def setPopupMenuEnabled(self, enabled: bool, /) -> None: ...
    def isPopupMenuEnabled(self) -> bool: ...
    def dump(self, filename: str, only_visible: bool = False, /) -> None: ...
    def dumpNode(self, node: object, /) -> str: ...
    def setStereoType(self, stereo_type: int | str, /) -> None: ...
    def getStereoType(self) -> str: ...
    def listStereoTypes(self) -> list[str]: ...
    def saveImage(
        self,
        filename: str,
        width: int = -1,
        height: int = -1,
        color: str = "Current",
        comment: str = "$MIBA",
        samples: int = 0,
        /,
    ) -> None: ...
    def saveVectorGraphic(
        self, filename: str, page_size: int = 4, background: str = "white", /
    ) -> None: ...
    def getCamera(self) -> str: ...
    def getCameraNode(self) -> Any: ...
    def getViewDirection(self) -> Any: ...
    def getUpDirection(self) -> Any: ...
    def setViewDirection(self, direction: object, /) -> None: ...
    def setCamera(self, camera: str, /) -> None: ...
    def setCameraOrientation(
        self, rotation: object, move_to_rotation_center: bool = False, /
    ) -> None: ...
    def getCameraOrientation(self) -> Any: ...
    def getCameraType(self) -> str: ...
    def setCameraType(self, camera_type: int | str, /) -> None: ...
    def listCameraTypes(self) -> list[str]: ...
    def getCursorPos(self) -> tuple[int, int]: ...
    def getObjectInfo(self, point: object, radius: float = 0.0, /) -> dict[str, Any] | None: ...
    def getObjectsInfo(
        self, point: object, radius: float = 0.0, /
    ) -> list[dict[str, Any]] | None: ...
    def getSize(self) -> tuple[int, int]: ...
    def getObjectInfoRay(self, *args: object) -> dict[str, Any] | None: ...
    def getPoint(self, x: int, y: int, /) -> Any: ...
    def getPointOnFocalPlane(self, x: int, y: int, /) -> Any: ...
    def getPointOnScreen(self, point: object, /) -> tuple[int, int]: ...
    def getPointOnViewport(self, point: object, /) -> tuple[int, int]: ...
    def projectPointToLine(self, x: int, y: int, /) -> tuple[Any, Any]: ...
    def addEventCallback(self, event_type: str, callback: object, /) -> object: ...
    def removeEventCallback(self, event_type: str, callback: object, /) -> None: ...
    def setAnnotation(self, name: str, buffer: str, /) -> None: ...
    def removeAnnotation(self, name: str, /) -> None: ...
    def getSceneGraph(self) -> Any: ...
    def getViewer(self) -> object: ...
    def addEventCallbackPivy(
        self, event_type: object, callback: object, extended: int = 1, /
    ) -> object: ...
    def removeEventCallbackPivy(
        self, event_type: object, callback: object, extended: int = 1, /
    ) -> object: ...
    def addEventCallbackSWIG(
        self, event_type: object, callback: object, extended: int = 1, /
    ) -> object: ...
    def removeEventCallbackSWIG(
        self, event_type: object, callback: object, extended: int = 1, /
    ) -> object: ...
    def listNavigationTypes(self) -> list[str]: ...
    def getNavigationType(self) -> str: ...
    def setNavigationType(self, navigation_type: str, /) -> None: ...
    def setAxisCross(self, enabled: bool, /) -> None: ...
    def hasAxisCross(self) -> bool: ...
    def addDraggerCallback(
        self, dragger: object, callback_type: str, callback: object, /
    ) -> object: ...
    def removeDraggerCallback(
        self, dragger: object, callback_type: str, callback: object, /
    ) -> object: ...
    def getViewProvidersOfType(self, type_name: str, /) -> list[object]: ...
    def redraw(self) -> None: ...
    def setName(self, name: str, /) -> None: ...
    def toggleClippingPlane(
        self,
        toggle: int = -1,
        beforeEditing: bool = False,
        noManip: bool = True,
        pla: object | None = None,
    ) -> None: ...
    def hasClippingPlane(self) -> bool: ...
    def graphicsView(self) -> Any: ...
    def setCornerCrossVisible(self, visible: bool, /) -> None: ...
    def isCornerCrossVisible(self) -> bool: ...
    def setCornerCrossSize(self, size: int, /) -> None: ...
    def getCornerCrossSize(self) -> int: ...
    def cast_to_base(self) -> object: ...
