# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

class TaskPlacement:
    def setPropertyName(self, name: str, /) -> None: ...
    def setPlacement(self, placement: object, /) -> None: ...
    def setSelection(self, selection: object, /) -> None: ...
    def bindObject(self) -> None: ...
    def setPlacementAndBindObject(self, document_object: object, property_name: str, /) -> None: ...
    def setIgnoreTransactions(self, ignore: bool, /) -> None: ...
    def showDefaultButtons(self, show: bool, /) -> None: ...
    def accept(self) -> bool: ...
    def reject(self) -> bool: ...
    def clicked(self, button: int, /) -> None: ...
    def open(self) -> None: ...
    def isAllowedAlterDocument(self) -> bool: ...
    def isAllowedAlterView(self) -> bool: ...
    def isAllowedAlterSelection(self) -> bool: ...
    def getStandardButtons(self) -> int: ...
