# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

class UiLoader:
    def load(self, source: object, parent: object | None = None, /) -> object | None: ...
    def createWidget(
        self, class_name: str, parent: object | None = None, name: str = "", /
    ) -> object | None: ...
    def availableWidgets(self) -> list[str]: ...
    def clearPluginPaths(self) -> None: ...
    def pluginPaths(self) -> list[str]: ...
    def addPluginPath(self, path: str, /) -> None: ...
    def errorString(self) -> str: ...
    def isLanguageChangeEnabled(self) -> bool: ...
    def setLanguageChangeEnabled(self, enabled: bool, /) -> None: ...
    def setWorkingDirectory(self, path: str, /) -> None: ...
    def workingDirectory(self) -> str: ...
