# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

class _UnitTest:
    def clearErrorList(self) -> None: ...
    def insertError(self, failure: str, details: str, /) -> None: ...
    def setUnitTest(self, unit: str, /) -> None: ...
    def getUnitTest(self) -> str: ...
    def setStatusText(self, text: str, /) -> None: ...
    def setProgressFraction(self, fraction: float, color: str = "", /) -> None: ...
    def errorDialog(self, title: str, message: str, /) -> None: ...
    def setRunCount(self, count: int, /) -> None: ...
    def setFailCount(self, count: int, /) -> None: ...
    def setErrorCount(self, count: int, /) -> None: ...
    def setRemainCount(self, count: int, /) -> None: ...
    def updateGUI(self) -> None: ...
    def addUnitTest(self, unit: str, /) -> None: ...
    def clearUnitTests(self) -> None: ...
