# SPDX-License-Identifier: LGPL-2.1-or-later

"""Shared target-kind strings for BIM Plan Edit."""

PLAN_TARGET_WALL = "wall"
PLAN_TARGET_OPENING = "opening"
PLAN_TARGET_SYMBOL = "symbol"
PLAN_TARGET_PROVIDER = "provider"
PLAN_TARGET_REGION = "region"
PLAN_TARGET_SPACE = "space"

PRIMARY_PLAN_TARGET_KINDS = (
    PLAN_TARGET_WALL,
    PLAN_TARGET_OPENING,
    PLAN_TARGET_SYMBOL,
    PLAN_TARGET_PROVIDER,
    PLAN_TARGET_REGION,
    PLAN_TARGET_SPACE,
)

SUMMARY_PLAN_TARGET_KINDS = (
    PLAN_TARGET_WALL,
    PLAN_TARGET_OPENING,
    PLAN_TARGET_SYMBOL,
    PLAN_TARGET_REGION,
    PLAN_TARGET_SPACE,
)

FOOTPRINT_PLAN_TARGET_KINDS = (
    PLAN_TARGET_SYMBOL,
    PLAN_TARGET_REGION,
    PLAN_TARGET_SPACE,
)

HOVERED_PLAN_TARGET_KINDS = (
    PLAN_TARGET_WALL,
    PLAN_TARGET_OPENING,
    PLAN_TARGET_SYMBOL,
    PLAN_TARGET_PROVIDER,
    PLAN_TARGET_SPACE,
    PLAN_TARGET_REGION,
)

PRIMARY_SELECTED_TARGET_PRIORITY_KINDS = (
    PLAN_TARGET_OPENING,
    PLAN_TARGET_SYMBOL,
    PLAN_TARGET_WALL,
    PLAN_TARGET_PROVIDER,
    PLAN_TARGET_REGION,
    PLAN_TARGET_SPACE,
)

PRIMARY_SELECTED_VISUAL_SYNC_KINDS = (
    PLAN_TARGET_OPENING,
    PLAN_TARGET_SYMBOL,
    PLAN_TARGET_REGION,
    PLAN_TARGET_SPACE,
)

CLEAR_PLAN_SELECTION_VISUAL_KINDS = (
    PLAN_TARGET_OPENING,
    PLAN_TARGET_SYMBOL,
    PLAN_TARGET_REGION,
    PLAN_TARGET_SPACE,
    PLAN_TARGET_PROVIDER,
)

PENDING_EDIT_VISUAL_SYNC_KINDS = (
    PLAN_TARGET_OPENING,
    PLAN_TARGET_SPACE,
    PLAN_TARGET_PROVIDER,
)

SEMANTIC_TARGET_CLEAR_HOVERED_KINDS = (
    PLAN_TARGET_WALL,
    PLAN_TARGET_OPENING,
    PLAN_TARGET_SYMBOL,
    PLAN_TARGET_SPACE,
    PLAN_TARGET_REGION,
)

SPACE_TARGET_CLEAR_HOVERED_KINDS = (
    PLAN_TARGET_WALL,
    PLAN_TARGET_OPENING,
    PLAN_TARGET_SYMBOL,
    PLAN_TARGET_REGION,
)

WALL_TARGET_CLEAR_HOVERED_KINDS = (
    PLAN_TARGET_WALL,
    PLAN_TARGET_SYMBOL,
    PLAN_TARGET_SPACE,
    PLAN_TARGET_REGION,
)

SPACE_EDIT_CLEAR_HOVERED_KINDS = (
    PLAN_TARGET_WALL,
    PLAN_TARGET_OPENING,
    PLAN_TARGET_SYMBOL,
    PLAN_TARGET_SPACE,
)

PLAN_REGION_CANCEL_VISUAL_KINDS = (
    PLAN_TARGET_REGION,
    PLAN_TARGET_SPACE,
    PLAN_TARGET_PROVIDER,
)

SPACE_SEPARATOR_CANCEL_VISUAL_KINDS = (
    PLAN_TARGET_OPENING,
    PLAN_TARGET_SPACE,
    PLAN_TARGET_PROVIDER,
)

EMBEDDED_TOOL_CLEAR_HOVERED_KINDS = (
    PLAN_TARGET_WALL,
    PLAN_TARGET_OPENING,
    PLAN_TARGET_SYMBOL,
    PLAN_TARGET_PROVIDER,
    PLAN_TARGET_REGION,
)
