# SPDX-License-Identifier: LGPL-2.1-or-later

"""Shared target-kind strings for BIM Plan Edit."""

PLAN_TARGET_WALL = "wall"
PLAN_TARGET_OPENING = "opening"
PLAN_TARGET_SYMBOL = "symbol"
PLAN_TARGET_PROVIDER = "provider"
PLAN_TARGET_REGION = "region"
PLAN_TARGET_SPACE = "space"

PRIMARY_PLAN_TARGET_KINDS = (
    PLAN_TARGET_WALL,
    PLAN_TARGET_OPENING,
    PLAN_TARGET_SYMBOL,
    PLAN_TARGET_PROVIDER,
    PLAN_TARGET_REGION,
    PLAN_TARGET_SPACE,
)

SUMMARY_PLAN_TARGET_KINDS = (
    PLAN_TARGET_WALL,
    PLAN_TARGET_OPENING,
    PLAN_TARGET_SYMBOL,
    PLAN_TARGET_REGION,
    PLAN_TARGET_SPACE,
)

FOOTPRINT_PLAN_TARGET_KINDS = (
    PLAN_TARGET_SYMBOL,
    PLAN_TARGET_REGION,
    PLAN_TARGET_SPACE,
)

HOVERED_PLAN_TARGET_KINDS = (
    PLAN_TARGET_WALL,
    PLAN_TARGET_OPENING,
    PLAN_TARGET_SYMBOL,
    PLAN_TARGET_PROVIDER,
    PLAN_TARGET_SPACE,
    PLAN_TARGET_REGION,
)
