# SPDX-License-Identifier: LGPL-2.1-or-later

"""Shared visual refresh keys for BIM Plan Edit overlays."""

PLAN_VISUAL_HOVERED_WALL = "hovered_wall"
PLAN_VISUAL_HOVERED_OPENING = "hovered_opening"
PLAN_VISUAL_HOVERED_SYMBOL = "hovered_symbol"
PLAN_VISUAL_HOVERED_PROVIDER = "hovered_provider"
PLAN_VISUAL_HOVERED_SPACE = "hovered_space"
PLAN_VISUAL_HOVERED_REGION = "hovered_region"
PLAN_VISUAL_SELECTED_PROVIDER = "selected_provider"
PLAN_VISUAL_SELECTED_OPENING = "selected_opening"
PLAN_VISUAL_SELECTED_SYMBOL = "selected_symbol"
PLAN_VISUAL_SELECTED_SPACE = "selected_space"
PLAN_VISUAL_SELECTED_REGION = "selected_region"
PLAN_VISUAL_SECONDARY_SELECTION = "secondary_selection"
PLAN_VISUAL_SPACE_REGION_PICK = "space_region_pick"
PLAN_VISUAL_WALL_GRIPS = "wall_grips"
PLAN_VISUAL_WALL_EDIT_PREVIEW = "wall_edit_preview"
PLAN_VISUAL_PROVIDER_OVERLAYS = "provider_overlays"
PLAN_VISUAL_VIEW_SCALE = "view_scale"
PLAN_VISUAL_ALL = "all"
