# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations
from typing import overload

@overload
def getImportType() -> _FileTypeModules: ...
@overload
def getImportType(extension: str, /) -> list[str]: ...
@overload
def getExportType() -> _FileTypeModules: ...
@overload
def getExportType(extension: str, /) -> list[str]: ...
def ParamGet(path: str, /) -> _ParameterGrp: ...
def saveParameter(name: str = "User parameter", /) -> None: ...
def Version() -> list[str]: ...
def ConfigGet(key: str, /) -> str: ...
def ConfigSet(key: str, value: str, /) -> None: ...
def ConfigDump() -> dict[str, str]: ...
def addImportType(extension: str, module: str, /) -> None: ...
def changeImportModule(extension: str, old_module: str, new_module: str, /) -> None: ...
def addExportType(extension: str, module: str, /) -> None: ...
def addTranslatableExportType(description: str, extensions: list[str], module: str, /) -> None: ...
def changeExportModule(extension: str, old_module: str, new_module: str, /) -> None: ...
def getResourceDir() -> str: ...
def getLibraryDir() -> str: ...
def getTempPath() -> str: ...
def getUserCachePath() -> str: ...
def getUserConfigDir() -> str: ...
def getUserAppDataDir() -> str: ...
def getUserMacroDir(actual: bool = False, /) -> str: ...
def getHelpDir() -> str: ...
def getHomePath() -> str: ...
def loadFile(path: str, doc: str = "", module: str = "", /) -> None: ...
def open(name: str, hidden: bool = False, temporary: bool = False) -> Document: ...
def openDocument(name: str, hidden: bool = False, temporary: bool = False) -> Document: ...
def newDocument(
    name: str | None = None,
    label: str | None = None,
    hidden: bool = False,
    temp: bool = False,
) -> Document: ...
def closeDocument(document: str | Document, /) -> None: ...
def activeDocument() -> Document | None: ...
def setActiveDocument(name: str, /) -> None: ...
def getDocument(name: str, /) -> Document: ...
def listDocuments(sort: bool = False, /) -> dict[str, Document]: ...
def addDocumentObserver(observer: object, /) -> None: ...
def removeDocumentObserver(observer: object, /) -> None: ...
def setLogLevel(tag: str, level: _LogLevelName | int, /) -> None: ...
def getLogLevel(tag: str, /) -> int: ...
def checkLinkDepth(depth: int, /) -> int: ...
def getLinksTo(
    obj: DocumentObject | None = None,
    options: int = 0,
    maxCount: int = 0,
    /,
) -> tuple[DocumentObject, ...]: ...
def getDependentObjects(
    obj: DocumentObject | Sequence[DocumentObject],
    options: int = 0,
    /,
) -> tuple[DocumentObject, ...]: ...
def setActiveTransaction(name: str, persist: bool = False, /) -> int: ...
def getActiveTransaction() -> tuple[str, int] | None: ...
def closeActiveTransaction(abort: bool = False, id: int = 0, /) -> None: ...
def isRestoring() -> bool: ...
def checkAbort() -> None: ...
