# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

class _ParameterGrp:
    def GetGroup(self, name: str, /) -> _ParameterGrp: ...
    def GetGroupName(self) -> str: ...
    def GetGroups(self) -> list[str]: ...
    def RemGroup(self, name: str, /) -> None: ...
    def HasGroup(self, name: str, /) -> bool: ...
    def RenameGroup(self, old_name: str, new_name: str, /) -> bool: ...
    def CopyTo(self, group: _ParameterGrp, /) -> None: ...
    def Manager(self) -> _ParameterGrp | None: ...
    def Parent(self) -> _ParameterGrp | None: ...
    def IsEmpty(self) -> bool: ...
    def Clear(self) -> None: ...
    def Attach(self, observer: object, /) -> None: ...
    def AttachManager(self, observer: object, /) -> None: ...
    def Detach(self, observer: object, /) -> None: ...
    def Notify(self, name: str, /) -> None: ...
    def NotifyAll(self) -> None: ...
    def SetBool(self, name: str, value: bool | int, /) -> None: ...
    def GetBool(self, name: str, default: bool | int = False, /) -> bool: ...
    def GetBools(self, filter: str = "", /) -> list[str]: ...
    def RemBool(self, name: str, /) -> None: ...
    def SetInt(self, name: str, value: int, /) -> None: ...
    def GetInt(self, name: str, default: int = 0, /) -> int: ...
    def GetInts(self, filter: str = "", /) -> list[str]: ...
    def RemInt(self, name: str, /) -> None: ...
    def SetUnsigned(self, name: str, value: int, /) -> None: ...
    def GetUnsigned(self, name: str, default: int = 0, /) -> int: ...
    def GetUnsigneds(self, filter: str = "", /) -> list[str]: ...
    def RemUnsigned(self, name: str, /) -> None: ...
    def SetFloat(self, name: str, value: float, /) -> None: ...
    def GetFloat(self, name: str, default: float = 0.0, /) -> float: ...
    def GetFloats(self, filter: str = "", /) -> list[str]: ...
    def RemFloat(self, name: str, /) -> None: ...
    def SetString(self, name: str, value: str, /) -> None: ...
    def GetString(self, name: str, default: str = "", /) -> str: ...
    def GetStrings(self, filter: str = "", /) -> list[str]: ...
    def RemString(self, name: str, /) -> None: ...
    def Import(self, path: str, /) -> None: ...
    def Insert(self, path: str, /) -> None: ...
    def Export(self, path: str, /) -> None: ...
    def GetContents(self) -> list[tuple[str, str, str | int | float | bool]] | None: ...
