class ArcOfEllipse:
    def __init__(
        self, ellipse: "Part.Ellipse", u1: float, u2: float, sense: bool = ..., /
    ) -> None: ...

class Feature:
    Shape: "Part.Shape" = ...

class Shape:
    BoundBox: "Part.BoundBox" = ...
    Placement: "Part.Placement" = ...
