#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-2.1-or-later

"""Generate typed Rust and C++ guest layers from the WASM API model."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
from typing import Any


CPP_KEYWORDS = {
    "class",
    "const",
    "enum",
    "explicit",
    "namespace",
    "struct",
    "template",
    "typename",
}
RUST_KEYWORDS = {
    "as",
    "crate",
    "enum",
    "extern",
    "fn",
    "impl",
    "in",
    "let",
    "match",
    "mod",
    "pub",
    "ref",
    "self",
    "struct",
    "trait",
    "type",
    "use",
}


def type_name(full_name: str, keywords: set[str]) -> str:
    parts = re.findall(r"[A-Za-z0-9]+", full_name)
    name = "".join(part[:1].upper() + part[1:] for part in parts) or "ApiType"
    if name[0].isdigit():
        name = f"Type{name}"
    if name.lower() in keywords:
        name += "Type"
    return f"{name}Handle"


def value_type_name(full_name: str, keywords: set[str]) -> str:
    handle_name = type_name(full_name, keywords)
    return f"{handle_name[:-len('Handle')]}Value"


def classes(model: dict[str, Any]) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    seen: set[str] = set()

    def add(full_name: str) -> None:
        if (
            not isinstance(full_name, str)
            or not full_name
            or full_name == "Wasm.Handle"
            or full_name in seen
        ):
            return
        seen.add(full_name)
        entries.append((full_name, type_name(full_name, CPP_KEYWORDS | RUST_KEYWORDS)))

    for api_class in model.get("classes", []):
        if api_class.get("representation", {}).get("kind") != "value":
            add(api_class.get("full_name"))
    for operation in model.get("operations", []):
        for parameter in operation.get("params", []):
            type_model = parameter.get("type", {})
            if type_model.get("kind") == "handle":
                add(type_model.get("type"))
        return_type = operation.get("returns", {})
        if return_type.get("kind") == "handle":
            add(return_type.get("type"))
    return entries


def value_types(model: dict[str, Any]) -> list[tuple[str, str, str]]:
    entries: list[tuple[str, str, str]] = []
    seen: set[str] = set()

    def add(full_name: str, encoding: str) -> None:
        if (
            not isinstance(full_name, str)
            or not full_name
            or full_name in seen
        ):
            return
        seen.add(full_name)
        entries.append(
            (
                full_name,
                value_type_name(full_name, CPP_KEYWORDS | RUST_KEYWORDS),
                encoding,
            )
        )

    for api_class in model.get("classes", []):
        representation = api_class.get("representation", {})
        if representation.get("kind") == "value":
            add(api_class.get("full_name"), representation.get("encoding", ""))
    for operation in model.get("operations", []):
        for parameter in operation.get("params", []):
            type_model = parameter.get("type", {})
            if type_model.get("kind") == "value":
                add(type_model.get("type"), type_model.get("encoding", ""))
        return_type = operation.get("returns", {})
        if return_type.get("kind") == "value":
            add(return_type.get("type"), return_type.get("encoding", ""))
    return entries


def render_cpp(model: dict[str, Any]) -> str:
    api = model.get("api", "org.freecad.wasm.api@0")
    class_names = dict(classes(model))
    value_names = {full_name: name for full_name, name, _ in value_types(model)}
    lines = [
        "// Generated by generate_wasm_sdk.py. Do not edit.",
        "#pragma once",
        "",
        "#include <Wasm/Guest/WasmGuest.h>",
        "",
        "namespace FreeCAD::Wasm::Generated",
        "{",
        f'inline constexpr char ApiVersion[] = "{api}";',
        "using Handle = unsigned long long;",
        "",
    ]
    for _, name in class_names.items():
        lines.extend(
            [
                f"struct {name}",
                "{",
                "    Handle value = 0U;",
                "",
                "    constexpr explicit operator bool() const { return value != 0U; }",
                "};",
                "",
            ]
        )
    for _, name, encoding in value_types(model):
        if encoding != "vector3-f64":
            raise ValueError(f"unsupported C++ Wasm value encoding: {encoding}")
        lines.extend(
            [
                f"struct {name}",
                "{",
                "    double x = 0.0;",
                "    double y = 0.0;",
                "    double z = 0.0;",
                "};",
                "",
            ]
        )

    lines.extend(
        [
            "class Host",
            "{",
            "public:",
            "    Host() = default;",
            "",
            "    explicit Host(::Wasm::Guest::Client client)",
            "        : client_(client)",
            "    {",
            "    }",
            "",
            "    auto allocateResponse(unsigned int size) const",
            "    {",
            "        return client_.allocateResponse(size);",
            "    }",
            "",
        ]
    )
    for operation in model.get("operations", []):
        params = operation.get("params", [])
        return_type = operation.get("returns", {})
        method = operation.get("guest_method", operation.get("name", ""))
        name = operation.get("name", "operation")
        lines.append(f"    // {operation.get('wire_name', name)}")
        permission = operation.get("permission")
        if permission:
            lines.append(
                f'    inline static constexpr char {name}Permission[] = "{permission}";'
            )
        lines.append(
            f"    inline static constexpr unsigned char {name}Operation = "
            f"{int(operation.get('id', 0))}U;"
        )

        parameter_declarations = []
        call_arguments = []
        for parameter in params:
            parameter_type = parameter.get("type", {})
            kind = parameter_type.get("kind")
            if kind == "string":
                cpp_type = "const char*"
            elif kind == "float64":
                cpp_type = "double"
            elif kind == "bool":
                cpp_type = "bool"
            elif kind == "value":
                cpp_type = value_names[parameter_type["type"]]
            elif kind == "handle":
                full_name = parameter_type.get("type")
                cpp_type = "Handle" if full_name == "Wasm.Handle" else class_names[full_name]
            else:
                cpp_type = "Handle"
            parameter_name = parameter.get("name", "value")
            parameter_declarations.append(f"{cpp_type} {parameter_name}")
            if kind == "handle" and parameter_type.get("type") != "Wasm.Handle":
                call_arguments.append(f"{parameter_name}.value")
            elif kind == "value" and parameter_type.get("encoding") == "vector3-f64":
                call_arguments.append(
                    "::Wasm::Guest::Vector3{"
                    f"{parameter_name}.x, {parameter_name}.y, {parameter_name}.z}}"
                )
            else:
                call_arguments.append(parameter_name)

        if return_type.get("kind") == "handle":
            result_type = return_type.get("type")
            result_cpp_type = "Handle" if result_type == "Wasm.Handle" else class_names[result_type]
            parameter_declarations.append(f"{result_cpp_type}* result")
            lines.append(
                f"    bool {name}({', '.join(parameter_declarations)}) const"
            )
            lines.extend(
                [
                    "    {",
                    "        if (result == nullptr) {",
                    "            return false;",
                    "        }",
                    "        ::Wasm::Guest::Handle raw = 0U;",
                    f"        if (!client_.{method}({', '.join(call_arguments + ['&raw'])})) {{",
                    "            return false;",
                    "        }",
                    "        result->value = raw;",
                    "        return true;",
                    "    }",
                    "",
                ]
            )
        elif return_type.get("kind") == "value":
            result_type = return_type.get("type")
            result_cpp_type = value_names[result_type]
            parameter_declarations.append(f"{result_cpp_type}* result")
            lines.append(
                f"    bool {name}({', '.join(parameter_declarations)}) const"
            )
            lines.extend(
                [
                    "    {",
                    "        if (result == nullptr) {",
                    "            return false;",
                    "        }",
                    "        ::Wasm::Guest::Vector3 raw;",
                    f"        if (!client_.{method}({', '.join(call_arguments + ['&raw'])})) {{",
                    "            return false;",
                    "        }",
                    "        result->x = raw.x;",
                    "        result->y = raw.y;",
                    "        result->z = raw.z;",
                    "        return true;",
                    "    }",
                    "",
                ]
            )
        elif return_type.get("kind") == "float64":
            parameter_declarations.append("double* result")
            lines.append(
                f"    bool {name}({', '.join(parameter_declarations)}) const"
            )
            lines.extend(
                [
                    "    {",
                    "        if (result == nullptr) {",
                    "            return false;",
                    "        }",
                    f"        return client_.{method}({', '.join(call_arguments + ['result'])});",
                    "    }",
                    "",
                ]
            )
        elif return_type.get("kind") == "bool":
            lines.append(
                f"    bool {name}({', '.join(parameter_declarations)}) const"
            )
            lines.extend(["    {"])
            if method == "release":
                lines.extend(
                    [
                        "#if defined(FREECAD_WASM_FREESTANDING)",
                        "        return client_.release(handle);",
                        "#else",
                        "        bool released = false;",
                        "        if (!client_.release(handle, &released)) {",
                        "            return false;",
                        "        }",
                        "        return released;",
                        "#endif",
                    ]
                )
            else:
                lines.append(f"        return client_.{method}({', '.join(call_arguments)});")
            lines.extend(["    }", ""])

    lines.extend(
        [
            "private:",
            "    ::Wasm::Guest::Client client_;",
            "};",
            "",
        ]
    )
    lines.extend(["}  // namespace FreeCAD::Wasm::Generated", ""])
    return "\n".join(lines)


def render_rust(model: dict[str, Any]) -> str:
    api = model.get("api", "org.freecad.wasm.api@0")
    lines = [
        "// Generated by generate_wasm_sdk.py. Do not edit.",
        "#![no_std]",
        "",
        f'pub const API_VERSION: &str = "{api}";',
        "pub type Handle = u64;",
        "",
    ]
    for _, name, encoding in value_types(model):
        if encoding != "vector3-f64":
            raise ValueError(f"unsupported Rust Wasm value encoding: {encoding}")
        lines.extend(
            [
                "#[repr(C)]",
                "#[derive(Clone, Copy, Debug, PartialEq)]",
                f"pub struct {name}",
                "{",
                "    pub x: f64,",
                "    pub y: f64,",
                "    pub z: f64,",
                "}",
                "",
            ]
        )
    for _, name in classes(model):
        lines.extend(
            [
                "#[repr(transparent)]",
                "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
                f"pub struct {name}(pub Handle);",
                "",
            ]
        )
    operations = model.get("operations", [])
    if operations:
        lines.extend(["pub mod operations {", ""])
        for operation in operations:
            constant = re.sub(
                r"[^A-Za-z0-9]+",
                "_",
                re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", operation.get("name", "operation")),
            ).upper()
            lines.append(f"    pub const {constant}: u8 = {int(operation.get('id', 0))};")
            permission = operation.get("permission")
            if permission:
                lines.append(
                    f'    pub const {constant}_PERMISSION: &str = "{permission}";'
                )
        lines.extend(["", "}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--api-json", required=True, type=Path)
    parser.add_argument("--cpp-output", required=True, type=Path)
    parser.add_argument("--rust-output", required=True, type=Path)
    args = parser.parse_args()

    model = json.loads(args.api_json.read_text(encoding="utf-8"))
    args.cpp_output.parent.mkdir(parents=True, exist_ok=True)
    args.rust_output.parent.mkdir(parents=True, exist_ok=True)
    args.cpp_output.write_text(render_cpp(model), encoding="utf-8")
    args.rust_output.write_text(render_rust(model), encoding="utf-8")


if __name__ == "__main__":
    main()
