#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-2.1-or-later

"""Generate typed Python, Rust, and C++ guest layers from the WASM API model."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
from typing import Any


CPP_KEYWORDS = {
    "class",
    "const",
    "enum",
    "explicit",
    "namespace",
    "struct",
    "template",
    "typename",
}
RUST_KEYWORDS = {
    "as",
    "crate",
    "enum",
    "extern",
    "fn",
    "impl",
    "in",
    "let",
    "match",
    "mod",
    "pub",
    "ref",
    "self",
    "struct",
    "trait",
    "type",
    "use",
}

_EXTENSION_FACADE_OPERATIONS = frozenset(
    {
        "documentNew",
        "documentGetObject",
        "documentAddObject",
        "documentIsSaved",
        "documentOpenTransaction",
        "documentCommitTransaction",
        "documentAbortTransaction",
        "documentObjectGetLabel",
        "documentObjectSetLabel",
        "partMakeBox",
        "topoShapeIsNull",
        "topoShapeIsValid",
        "topoShapeLength",
        "topoShapeArea",
        "topoShapeVolume",
        "vectorNew",
        "vectorAdd",
        "vectorSub",
        "vectorDot",
        "vectorCross",
    }
)


def has_extension_facade(model: dict[str, Any]) -> bool:
    """Return whether the current model contains the complete facade slice."""

    operation_names = {operation.get("name") for operation in model.get("operations", [])}
    return _EXTENSION_FACADE_OPERATIONS.issubset(operation_names)


def type_name(full_name: str, keywords: set[str]) -> str:
    parts = re.findall(r"[A-Za-z0-9]+", full_name)
    name = "".join(part[:1].upper() + part[1:] for part in parts) or "ApiType"
    if name[0].isdigit():
        name = f"Type{name}"
    if name.lower() in keywords:
        name += "Type"
    return f"{name}Handle"


def value_type_name(full_name: str, keywords: set[str]) -> str:
    handle_name = type_name(full_name, keywords)
    return f"{handle_name[:-len('Handle')]}Value"


def rust_method_name(name: str) -> str:
    return re.sub(
        r"[^a-zA-Z0-9]+",
        "_",
        re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name),
    ).lower()


def operation_constant_name(name: str) -> str:
    return rust_method_name(name).upper()


def classes(model: dict[str, Any]) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    seen: set[str] = set()

    def add(full_name: str) -> None:
        if (
            not isinstance(full_name, str)
            or not full_name
            or full_name == "Wasm.Handle"
            or full_name in seen
        ):
            return
        seen.add(full_name)
        entries.append((full_name, type_name(full_name, CPP_KEYWORDS | RUST_KEYWORDS)))

    for api_class in model.get("classes", []):
        if api_class.get("representation", {}).get("kind") != "value":
            add(api_class.get("full_name"))
    for operation in model.get("operations", []):
        for parameter in operation.get("params", []):
            type_model = parameter.get("type", {})
            if type_model.get("kind") == "handle":
                add(type_model.get("type"))
        return_type = operation.get("returns", {})
        if return_type.get("kind") == "handle":
            add(return_type.get("type"))
    return entries


def value_types(model: dict[str, Any]) -> list[tuple[str, str, str]]:
    entries: list[tuple[str, str, str]] = []
    seen: set[str] = set()

    def add(full_name: str, encoding: str) -> None:
        if (
            not isinstance(full_name, str)
            or not full_name
            or full_name in seen
        ):
            return
        seen.add(full_name)
        entries.append(
            (
                full_name,
                value_type_name(full_name, CPP_KEYWORDS | RUST_KEYWORDS),
                encoding,
            )
        )

    for api_class in model.get("classes", []):
        representation = api_class.get("representation", {})
        if representation.get("kind") == "value":
            add(api_class.get("full_name"), representation.get("encoding", ""))
    for operation in model.get("operations", []):
        for parameter in operation.get("params", []):
            type_model = parameter.get("type", {})
            if type_model.get("kind") == "value":
                add(type_model.get("type"), type_model.get("encoding", ""))
        return_type = operation.get("returns", {})
        if return_type.get("kind") == "value":
            add(return_type.get("type"), return_type.get("encoding", ""))
    return entries


def render_cpp(model: dict[str, Any]) -> str:
    api = model.get("api", "org.freecad.wasm.api@0")
    abi = model.get("abi", {})
    class_names = dict(classes(model))
    value_names = {full_name: name for full_name, name, _ in value_types(model)}
    lines = [
        "// Generated by generate_wasm_sdk.py. Do not edit.",
        "#pragma once",
        "",
        "#include <Wasm/Guest/WasmGuest.h>",
        "",
        "namespace FreeCAD::Extension::Raw",
        "{",
        f'inline constexpr char ApiVersion[] = "{api}";',
        f'inline constexpr char ApiCatalogSignature[] = "{abi.get("catalog_signature", "")}";',
        f'inline constexpr char ResponseMagic[] = "{abi.get("response_magic", "FCWR")}";',
        f"inline constexpr unsigned char ResponseVersion = {int(abi.get('response_version', 1))}U;",
        f"inline constexpr unsigned char ResponseHeaderSize = {int(abi.get('response_header_size', 12))}U;",
        "using Handle = unsigned long long;",
        "",
    ]
    for _, name in class_names.items():
        lines.extend(
            [
                f"struct {name}",
                "{",
                "    Handle value = 0U;",
                "",
                "    constexpr explicit operator bool() const { return value != 0U; }",
                "};",
                "",
            ]
        )
    for _, name, encoding in value_types(model):
        if encoding != "vector3-f64":
            raise ValueError(f"unsupported C++ Wasm value encoding: {encoding}")
        lines.extend(
            [
                f"struct {name}",
                "{",
                "    double x = 0.0;",
                "    double y = 0.0;",
                "    double z = 0.0;",
                "};",
                "",
            ]
        )

    lines.extend(
        [
            "class OwnedHandle",
            "{",
            "public:",
            "    OwnedHandle() = default;",
            "",
            "    OwnedHandle(::Wasm::Guest::Client client, Handle value)",
            "        : client_(client)",
            "        , value(value)",
            "    {",
            "    }",
            "",
            "    ~OwnedHandle()",
            "    {",
            "        reset();",
            "    }",
            "",
            "    OwnedHandle(const OwnedHandle&) = delete;",
            "    OwnedHandle& operator=(const OwnedHandle&) = delete;",
            "",
            "    OwnedHandle(OwnedHandle&& other) noexcept",
            "        : client_(other.client_)",
            "        , value(other.value)",
            "    {",
            "        other.value = 0U;",
            "    }",
            "",
            "    OwnedHandle& operator=(OwnedHandle&& other) noexcept",
            "    {",
            "        if (this != &other) {",
            "            reset();",
            "            client_ = other.client_;",
            "            value = other.value;",
            "            other.value = 0U;",
            "        }",
            "        return *this;",
            "    }",
            "",
            "    explicit operator bool() const { return value != 0U; }",
            "    Handle get() const { return value; }",
            "",
            "    void reset()",
            "    {",
            "        if (value != 0U) {",
            "            static_cast<void>(client_.release(value));",
            "        }",
            "        value = 0U;",
            "    }",
            "",
            "private:",
            "    ::Wasm::Guest::Client client_;",
            "    Handle value = 0U;",
            "};",
            "",
            "class RawClient",
            "{",
            "public:",
            "    RawClient() = default;",
            "",
            "    explicit RawClient(::Wasm::Guest::Client client)",
            "        : client_(client)",
            "    {",
            "    }",
            "",
            "    auto allocateResponse(unsigned int size) const",
            "    {",
            "        return client_.allocateResponse(size);",
            "    }",
            "",
            "    OwnedHandle own(Handle value)",
            "    {",
            "        return OwnedHandle(client_, value);",
            "    }",
            "",
        ]
    )
    for operation in model.get("operations", []):
        params = operation.get("params", [])
        return_type = operation.get("returns", {})
        method = operation.get("guest_method", operation.get("name", ""))
        name = operation.get("name", "operation")
        lines.append(f"    // {operation.get('wire_name', name)}")
        permission = operation.get("permission")
        if permission:
            lines.append(
                f'    inline static constexpr char {name}Permission[] = "{permission}";'
            )
        returns_metadata = return_type
        if returns_metadata.get("kind") == "handle":
            lines.append(
                f'    inline static constexpr char {name}Ownership[] = "{returns_metadata.get("ownership", "borrowed")}";'
            )
        if operation.get("transaction"):
            lines.append(
                f'    inline static constexpr char {name}Transaction[] = "{operation["transaction"]}";'
            )
        lines.append(
            f"    inline static constexpr unsigned char {name}Operation = "
            f"{int(operation.get('id', 0))}U;"
        )
        lines.append(
            f"    inline static constexpr bool {name}Fallible = "
            f"{'true' if operation.get('fallible', True) else 'false'};"
        )
        lines.append(
            f"    inline static constexpr bool {name}Nullable = "
            f"{'true' if return_type.get('nullable', False) else 'false'};"
        )
        lines.append(
            f"    inline static constexpr bool {name}Consumes = "
            f"{'true' if operation.get('consumes', False) else 'false'};"
        )

        parameter_declarations = []
        call_arguments = []
        for parameter in params:
            parameter_type = parameter.get("type", {})
            kind = parameter_type.get("kind")
            if kind == "string":
                cpp_type = "const char*"
            elif kind == "float64":
                cpp_type = "double"
            elif kind == "bool":
                cpp_type = "bool"
            elif kind == "value":
                cpp_type = value_names[parameter_type["type"]]
            elif kind == "handle":
                full_name = parameter_type.get("type")
                cpp_type = "Handle" if full_name == "Wasm.Handle" else class_names[full_name]
            else:
                cpp_type = "Handle"
            parameter_name = parameter.get("name", "value")
            parameter_declarations.append(f"{cpp_type} {parameter_name}")
            if kind == "handle" and parameter_type.get("type") != "Wasm.Handle":
                call_arguments.append(f"{parameter_name}.value")
            elif kind == "value" and parameter_type.get("encoding") == "vector3-f64":
                call_arguments.append(
                    "::Wasm::Guest::Vector3{"
                    f"{parameter_name}.x, {parameter_name}.y, {parameter_name}.z}}"
                )
            else:
                call_arguments.append(parameter_name)

        result_parameter_declarations = list(parameter_declarations)

        if return_type.get("kind") == "string":
            parameter_declarations.extend(
                ["char* result", "unsigned int capacity", "unsigned int* length"]
            )
            lines.append(
                f"    bool {name}({', '.join(parameter_declarations)}) const"
            )
            lines.extend(
                [
                    "    {",
                    "        if (length == nullptr || (capacity != 0U && result == nullptr)) {",
                    "            return false;",
                    "        }",
                    f"        return client_.{method}({', '.join(call_arguments + ['result', 'capacity', 'length'])});",
                    "    }",
                    "",
                ]
            )
        elif return_type.get("kind") == "handle":
            result_type = return_type.get("type")
            result_cpp_type = "Handle" if result_type == "Wasm.Handle" else class_names[result_type]
            parameter_declarations.append(f"{result_cpp_type}* result")
            lines.append(
                f"    bool {name}({', '.join(parameter_declarations)}) const"
            )
            lines.extend(
                [
                    "    {",
                    "        if (result == nullptr) {",
                    "            return false;",
                    "        }",
                    "        ::Wasm::Guest::Handle raw = 0U;",
                    f"        if (!client_.{method}({', '.join(call_arguments + ['&raw'])})) {{",
                    "            return false;",
                    "        }",
                    "        result->value = raw;",
                    "        return true;",
                    "    }",
                    "",
                ]
            )
        elif return_type.get("kind") == "value":
            result_type = return_type.get("type")
            result_cpp_type = value_names[result_type]
            parameter_declarations.append(f"{result_cpp_type}* result")
            lines.append(
                f"    bool {name}({', '.join(parameter_declarations)}) const"
            )
            lines.extend(
                [
                    "    {",
                    "        if (result == nullptr) {",
                    "            return false;",
                    "        }",
                    "        ::Wasm::Guest::Vector3 raw;",
                    f"        if (!client_.{method}({', '.join(call_arguments + ['&raw'])})) {{",
                    "            return false;",
                    "        }",
                    "        result->x = raw.x;",
                    "        result->y = raw.y;",
                    "        result->z = raw.z;",
                    "        return true;",
                    "    }",
                    "",
                ]
            )
        elif return_type.get("kind") == "float64":
            parameter_declarations.append("double* result")
            lines.append(
                f"    bool {name}({', '.join(parameter_declarations)}) const"
            )
            lines.extend(
                [
                    "    {",
                    "        if (result == nullptr) {",
                    "            return false;",
                    "        }",
                    f"        return client_.{method}({', '.join(call_arguments + ['result'])});",
                    "    }",
                    "",
                ]
            )
        elif return_type.get("kind") == "bool":
            lines.append(
                f"    bool {name}({', '.join(parameter_declarations)}) const"
            )
            lines.extend(["    {"])
            if method == "release":
                lines.extend(
                    [
                        "#if defined(FREECAD_WASM_FREESTANDING)",
                        "        return client_.release(handle);",
                        "#else",
                        "        bool released = false;",
                        "        if (!client_.release(handle, &released)) {",
                        "            return false;",
                        "        }",
                        "        return released;",
                        "#endif",
                    ]
                )
            else:
                lines.extend(
                    [
                        "        bool value = false;",
                        f"        if (!client_.{method}({', '.join(call_arguments + ['&value'])})) {{",
                        "            return false;",
                        "        }",
                        "        return value;",
                    ]
                )
            lines.extend(["    }", ""])
        elif return_type.get("kind") == "none":
            lines.append(
                f"    bool {name}({', '.join(parameter_declarations)}) const"
            )
            lines.extend(
                [
                    "    {",
                    f"        return client_.{method}({', '.join(call_arguments)});",
                    "    }",
                    "",
                ]
            )

        # Hosted guests can use the structured transport result directly. Keep
        # the bool/out-parameter adapters above for freestanding guests.
        result_kinds = {
            "handle": "::Wasm::Guest::Handle",
            "value": "::Wasm::Guest::Vector3",
            "float64": "double",
            "bool": "bool",
            "string": "std::string",
            "none": "void",
        }
        result_cpp_type = result_kinds.get(return_type.get("kind"))
        if result_cpp_type is None:
            raise ValueError(f"unsupported C++ Wasm result type: {return_type.get('kind')}")
        result_call_arguments = [
            f"std::string_view({argument})"
            if parameter.get("type", {}).get("kind") == "string"
            else argument
            for parameter, argument in zip(params, call_arguments)
        ]
        lines.extend(
            [
                "#if !defined(FREECAD_WASM_FREESTANDING)",
                f"    ::Wasm::Guest::Result<{result_cpp_type}> {name}Result({', '.join(result_parameter_declarations)}) const",
                "    {",
            ]
        )
        for parameter in params:
            if parameter.get("type", {}).get("kind") == "string":
                parameter_name = parameter.get("name", "value")
                lines.extend(
                    [
                        f"        if ({parameter_name} == nullptr) {{",
                        (
                            '            return {false, "string parameter is null", '
                            '::Wasm::Abi::ErrorCode::InvalidRequest};'
                            if return_type.get("kind") == "none"
                            else '            return {false, {}, "string parameter is null"};'
                        ),
                        "        }",
                    ]
                )
        lines.append(
            f"        return client_.{method}({', '.join(result_call_arguments)});"
        )
        lines.extend(["    }", "#endif", ""])

    lines.extend(
        [
            "private:",
            "    ::Wasm::Guest::Client client_;",
            "};",
            "",
            "using Client = RawClient;",
            "",
        ]
    )
    lines.extend(
        [
            "}  // namespace FreeCAD::Extension::Raw",
            "",
            "// Compatibility namespace for existing experimental addons.",
            "namespace FreeCAD::Wasm::Generated",
            "{",
            "using namespace ::FreeCAD::Extension::Raw;",
            "}  // namespace FreeCAD::Wasm::Generated",
            "",
        ]
    )
    if has_extension_facade(model):
        lines.extend(_cpp_extension_facade())
    return "\n".join(lines)


def _cpp_extension_facade() -> list[str]:
    """Render the hosted C++ facade over the generated raw client."""

    return [
        "",
        "#if !defined(FREECAD_WASM_FREESTANDING)",
        "namespace FreeCAD::Extension",
        "{",
        "using RawClient = Raw::RawClient;",
        "template<typename T>",
        "using Result = ::Wasm::Guest::Result<T>;",
        "",
        "inline Result<void> checkResult(Result<bool> result, const char* message)",
        "{",
        "    if (!result.ok) {",
        "        return {false, std::move(result.error), result.errorCode};",
        "    }",
        "    if (!result.value) {",
        "        return {false, message, ::Wasm::Abi::ErrorCode::HostFailure};",
        "    }",
        "    return {true, {}, ::Wasm::Abi::ErrorCode::None};",
        "}",
        "",
        "inline std::string extensionString(std::string_view value)",
        "{",
        "    return std::string(value);",
        "}",
        "",
        "class Resource",
        "{",
        "public:",
        "    Resource() = default;",
        "    ~Resource() { reset(); }",
        "    Resource(const Resource&) = delete;",
        "    Resource& operator=(const Resource&) = delete;",
        "",
        "    Resource(Resource&& other) noexcept",
        "        : client_(other.client_)",
        "        , value_(other.value_)",
        "        , owned_(other.owned_)",
        "    {",
        "        other.value_ = 0U;",
        "        other.owned_ = false;",
        "    }",
        "",
        "    Resource& operator=(Resource&& other) noexcept",
        "    {",
        "        if (this != &other) {",
        "            reset();",
        "            client_ = other.client_;",
        "            value_ = other.value_;",
        "            owned_ = other.owned_;",
        "            other.value_ = 0U;",
        "            other.owned_ = false;",
        "        }",
        "        return *this;",
        "    }",
        "",
        "    explicit operator bool() const { return value_ != 0U; }",
        "    Raw::Handle value() const { return value_; }",
        "",
        "protected:",
        "    Resource(RawClient client, Raw::Handle value, bool owned)",
        "        : client_(client)",
        "        , value_(value)",
        "        , owned_(owned)",
        "    {",
        "    }",
        "",
        "    void reset()",
        "    {",
        "        if (owned_ && value_ != 0U) {",
        "            static_cast<void>(client_.release(value_));",
        "        }",
        "        value_ = 0U;",
        "        owned_ = false;",
        "    }",
        "",
        "    RawClient client_;",
        "    Raw::Handle value_ = 0U;",
        "    bool owned_ = false;",
        "};",
        "",
        "class DocumentObject final: public Resource",
        "{",
        "public:",
        "    DocumentObject() = default;",
        "",
        "    Result<std::string> label() const",
        "    {",
        "        return client_.documentObjectGetLabelResult(Raw::FreeCADDocumentObjectHandle{value_});",
        "    }",
        "",
        "    Result<void> setLabel(std::string_view label) const",
        "    {",
        "        auto value = extensionString(label);",
        "        return client_.documentObjectSetLabelResult(Raw::FreeCADDocumentObjectHandle{value_}, value.c_str());",
        "    }",
        "",
        "private:",
        "    friend class Document;",
        "    DocumentObject(RawClient client, Raw::Handle value, bool owned)",
        "        : Resource(client, value, owned)",
        "    {",
        "    }",
        "};",
        "",
        "class TopoShape final: public Resource",
        "{",
        "public:",
        "    TopoShape() = default;",
        "",
        "    Result<bool> isNull() const",
        "    {",
        "        return client_.topoShapeIsNullResult(Raw::PartTopoShapeHandle{value_});",
        "    }",
        "",
        "    Result<bool> isValid() const",
        "    {",
        "        return client_.topoShapeIsValidResult(Raw::PartTopoShapeHandle{value_});",
        "    }",
        "",
        "    Result<double> length() const",
        "    {",
        "        return client_.topoShapeLengthResult(Raw::PartTopoShapeHandle{value_});",
        "    }",
        "",
        "    Result<double> area() const",
        "    {",
        "        return client_.topoShapeAreaResult(Raw::PartTopoShapeHandle{value_});",
        "    }",
        "",
        "    Result<double> volume() const",
        "    {",
        "        return client_.topoShapeVolumeResult(Raw::PartTopoShapeHandle{value_});",
        "    }",
        "",
        "private:",
        "    friend class Document;",
        "    friend class Part;",
        "    TopoShape(RawClient client, Raw::Handle value, bool owned)",
        "        : Resource(client, value, owned)",
        "    {",
        "    }",
        "};",
        "",
        "class Transaction final",
        "{",
        "public:",
        "    Transaction() = default;",
        "    ~Transaction()",
        "    {",
        "        if (active_) {",
        "            static_cast<void>(client_.documentAbortTransactionResult(document_));",
        "        }",
        "    }",
        "    Transaction(const Transaction&) = delete;",
        "    Transaction& operator=(const Transaction&) = delete;",
        "",
        "    Transaction(Transaction&& other) noexcept",
        "        : client_(other.client_)",
        "        , document_(other.document_)",
        "        , active_(other.active_)",
        "    {",
        "        other.active_ = false;",
        "    }",
        "",
        "    Result<void> commit()",
        "    {",
        "        if (!active_) {",
        "            return {true, {}, ::Wasm::Abi::ErrorCode::None};",
        "        }",
        "        auto result = checkResult(client_.documentCommitTransactionResult(document_),",
        "                                   \"host rejected transaction commit\");",
        "        if (result.ok) {",
        "            active_ = false;",
        "        }",
        "        return result;",
        "    }",
        "",
        "    Result<void> abort()",
        "    {",
        "        if (!active_) {",
        "            return {true, {}, ::Wasm::Abi::ErrorCode::None};",
        "        }",
        "        auto result = checkResult(client_.documentAbortTransactionResult(document_),",
        "                                   \"host rejected transaction abort\");",
        "        if (result.ok) {",
        "            active_ = false;",
        "        }",
        "        return result;",
        "    }",
        "",
        "private:",
        "    friend class Document;",
        "    Transaction(RawClient client, Raw::FreeCADDocumentHandle document)",
        "        : client_(client)",
        "        , document_(document)",
        "        , active_(true)",
        "    {",
        "    }",
        "",
        "    RawClient client_;",
        "    Raw::FreeCADDocumentHandle document_;",
        "    bool active_ = false;",
        "};",
        "",
        "class Document final: public Resource",
        "{",
        "public:",
        "    Document() = default;",
        "",
        "    Result<bool> isSaved() const",
        "    {",
        "        return client_.documentIsSavedResult(Raw::FreeCADDocumentHandle{value_});",
        "    }",
        "",
        "    Result<DocumentObject> getObject(std::string_view name) const",
        "    {",
        "        auto value = extensionString(name);",
        "        auto result = client_.documentGetObjectResult(Raw::FreeCADDocumentHandle{value_}, value.c_str());",
        "        if (!result.ok) {",
        "            return {false, {}, std::move(result.error), result.errorCode};",
        "        }",
        "        return {true, DocumentObject(client_, result.value, true), {}, ::Wasm::Abi::ErrorCode::None};",
        "    }",
        "",
        "    Result<DocumentObject> addObject(const TopoShape& shape, std::string_view name) const",
        "    {",
        "        auto value = extensionString(name);",
        "        auto result = client_.documentAddObjectResult(",
        "            Raw::FreeCADDocumentHandle{value_},",
        "            Raw::PartTopoShapeHandle{shape.value()},",
        "            value.c_str());",
        "        if (!result.ok) {",
        "            return {false, {}, std::move(result.error), result.errorCode};",
        "        }",
        "        return {true, DocumentObject(client_, result.value, true), {}, ::Wasm::Abi::ErrorCode::None};",
        "    }",
        "",
        "    Result<Transaction> transaction(std::string_view name) const",
        "    {",
        "        auto value = extensionString(name);",
        "        auto result = client_.documentOpenTransactionResult(",
        "            Raw::FreeCADDocumentHandle{value_}, value.c_str());",
        "        auto checked = checkResult(std::move(result), \"host rejected document transaction\");",
        "        if (!checked.ok) {",
        "            return {false, {}, std::move(checked.error), checked.errorCode};",
        "        }",
        "        return {true, Transaction(client_, Raw::FreeCADDocumentHandle{value_}), {},",
        "                ::Wasm::Abi::ErrorCode::None};",
        "    }",
        "",
        "private:",
        "    friend class Documents;",
        "    Document(RawClient client, Raw::Handle value, bool owned)",
        "        : Resource(client, value, owned)",
        "    {",
        "    }",
        "};",
        "",
        "class Part final",
        "{",
        "public:",
        "    explicit Part(RawClient client)",
        "        : client_(client)",
        "    {",
        "    }",
        "",
        "    Result<TopoShape> makeBox(double length, double width, double height) const",
        "    {",
        "        auto result = client_.partMakeBoxResult(length, width, height);",
        "        if (!result.ok) {",
        "            return {false, {}, std::move(result.error), result.errorCode};",
        "        }",
        "        return {true, TopoShape(client_, result.value, true), {}, ::Wasm::Abi::ErrorCode::None};",
        "    }",
        "",
        "private:",
        "    RawClient client_;",
        "};",
        "",
        "class Vector final",
        "{",
        "public:",
        "    Vector() = default;",
        "    double x() const { return value_.x; }",
        "    double y() const { return value_.y; }",
        "    double z() const { return value_.z; }",
        "",
        "    Result<Vector> add(const Vector& other) const;",
        "    Result<Vector> sub(const Vector& other) const;",
        "    Result<double> dot(const Vector& other) const;",
        "    Result<Vector> cross(const Vector& other) const;",
        "",
        "private:",
        "    friend class Geometry;",
        "    Vector(RawClient client, Raw::FreeCADBaseVectorValue value)",
        "        : client_(client)",
        "        , value_(value)",
        "    {",
        "    }",
        "",
        "    RawClient client_;",
        "    Raw::FreeCADBaseVectorValue value_;",
        "};",
        "",
        "inline Result<Vector> Vector::add(const Vector& other) const",
        "{",
        "    auto result = client_.vectorAddResult(value_, other.value_);",
        "    if (!result.ok) {",
        "        return {false, {}, std::move(result.error), result.errorCode};",
        "    }",
        "    return {true, Vector(client_, Raw::FreeCADBaseVectorValue{result.value.x, result.value.y, result.value.z}), {},",
        "            ::Wasm::Abi::ErrorCode::None};",
        "}",
        "",
        "inline Result<Vector> Vector::sub(const Vector& other) const",
        "{",
        "    auto result = client_.vectorSubResult(value_, other.value_);",
        "    if (!result.ok) {",
        "        return {false, {}, std::move(result.error), result.errorCode};",
        "    }",
        "    return {true, Vector(client_, Raw::FreeCADBaseVectorValue{result.value.x, result.value.y, result.value.z}), {},",
        "            ::Wasm::Abi::ErrorCode::None};",
        "}",
        "",
        "inline Result<double> Vector::dot(const Vector& other) const",
        "{",
        "    return client_.vectorDotResult(value_, other.value_);",
        "}",
        "",
        "inline Result<Vector> Vector::cross(const Vector& other) const",
        "{",
        "    auto result = client_.vectorCrossResult(value_, other.value_);",
        "    if (!result.ok) {",
        "        return {false, {}, std::move(result.error), result.errorCode};",
        "    }",
        "    return {true, Vector(client_, Raw::FreeCADBaseVectorValue{result.value.x, result.value.y, result.value.z}), {},",
        "            ::Wasm::Abi::ErrorCode::None};",
        "}",
        "",
        "class Documents final",
        "{",
        "public:",
        "    explicit Documents(RawClient client)",
        "        : client_(client)",
        "    {",
        "    }",
        "",
        "    Result<Document> create(std::string_view name) const",
        "    {",
        "        auto value = extensionString(name);",
        "        auto result = client_.documentNewResult(value.c_str());",
        "        if (!result.ok) {",
        "            return {false, {}, std::move(result.error), result.errorCode};",
        "        }",
        "        return {true, Document(client_, result.value, true), {}, ::Wasm::Abi::ErrorCode::None};",
        "    }",
        "",
        "private:",
        "    RawClient client_;",
        "};",
        "",
        "class Geometry final",
        "{",
        "public:",
        "    explicit Geometry(RawClient client)",
        "        : client_(client)",
        "    {",
        "    }",
        "",
        "    Result<Vector> vector(double x, double y, double z) const",
        "    {",
        "        auto result = client_.vectorNewResult(x, y, z);",
        "        if (!result.ok) {",
        "            return {false, {}, std::move(result.error), result.errorCode};",
        "        }",
        "        return {true, Vector(client_, Raw::FreeCADBaseVectorValue{result.value.x, result.value.y, result.value.z}), {},",
        "                ::Wasm::Abi::ErrorCode::None};",
        "    }",
        "",
        "private:",
        "    RawClient client_;",
        "};",
        "",
        "class Extension final",
        "{",
        "public:",
        "    explicit Extension(RawClient client = RawClient())",
        "        : client_(client)",
        "    {",
        "    }",
        "",
        "    RawClient& raw() { return client_; }",
        "    const RawClient& raw() const { return client_; }",
        "    Documents documents() const { return Documents(client_); }",
        "    Part part() const { return Part(client_); }",
        "    Geometry geometry() const { return Geometry(client_); }",
        "",
        "private:",
        "    RawClient client_;",
        "};",
        "",
        "}  // namespace FreeCAD::Extension",
        "#endif",
        "",
    ]


def _python_extension_facade() -> list[str]:
    """Render the public Python facade over the generated raw client."""

    return [
        "",
        "",
        "class _Resource:",
        "    \"\"\"Opaque extension resource with optional host ownership.\"\"\"",
        "",
        "    def __init__(self, client: RawClient, value: int, owned: bool = False):",
        "        self._client = client",
        "        self._value = int(value)",
        "        self._owned = owned",
        "        self._closed = False",
        "",
        "    @property",
        "    def value(self) -> int:",
        "        return self._value",
        "",
        "    def close(self) -> None:",
        "        if self._owned and not self._closed:",
        "            self._client.release(self._value)",
        "            self._closed = True",
        "",
        "    def __enter__(self):",
        "        return self",
        "",
        "    def __exit__(self, _type, _value, _traceback) -> None:",
        "        self.close()",
        "",
        "",
        "class Document(_Resource):",
        "    def is_saved(self) -> bool:",
        "        return self._client.document_is_saved(FreeCADDocumentHandle(self._value))",
        "",
        "    def get_object(self, name: str) -> DocumentObject:",
        "        value = self._client.document_get_object(FreeCADDocumentHandle(self._value), name)",
        "        return DocumentObject(self._client, value, owned=True)",
        "",
        "    def add_object(self, shape: TopoShape, name: str) -> DocumentObject:",
        "        value = self._client.document_add_object(",
        "            FreeCADDocumentHandle(self._value),",
        "            PartTopoShapeHandle(shape.value),",
        "            name,",
        "        )",
        "        return DocumentObject(self._client, value, owned=True)",
        "",
        "    def transaction(self, name: str) -> Transaction:",
        "        return Transaction(self, name)",
        "",
        "",
        "class DocumentObject(_Resource):",
        "    @property",
        "    def label(self) -> str:",
        "        return self._client.document_object_get_label(",
        "            FreeCADDocumentObjectHandle(self._value)",
        "        )",
        "",
        "    @label.setter",
        "    def label(self, value: str) -> None:",
        "        self._client.document_object_set_label(",
        "            FreeCADDocumentObjectHandle(self._value), value",
        "        )",
        "",
        "",
        "class TopoShape(_Resource):",
        "    def is_null(self) -> bool:",
        "        return self._client.topo_shape_is_null(PartTopoShapeHandle(self._value))",
        "",
        "    def is_valid(self) -> bool:",
        "        return self._client.topo_shape_is_valid(PartTopoShapeHandle(self._value))",
        "",
        "    @property",
        "    def length(self) -> float:",
        "        return self._client.topo_shape_length(PartTopoShapeHandle(self._value))",
        "",
        "    @property",
        "    def area(self) -> float:",
        "        return self._client.topo_shape_area(PartTopoShapeHandle(self._value))",
        "",
        "    @property",
        "    def volume(self) -> float:",
        "        return self._client.topo_shape_volume(PartTopoShapeHandle(self._value))",
        "",
        "",
        "@dataclass",
        "class Vector:",
        "    _client: RawClient",
        "    x: float",
        "    y: float",
        "    z: float",
        "",
        "    def _value(self) -> FreeCADBaseVectorValue:",
        "        return FreeCADBaseVectorValue(self.x, self.y, self.z)",
        "",
        "    @classmethod",
        "    def _from_value(cls, client: RawClient, value: FreeCADBaseVectorValue):",
        "        return cls(client, value.x, value.y, value.z)",
        "",
        "    def add(self, other: Vector) -> Vector:",
        "        return self._from_value(self._client, self._client.vector_add(self._value(), other._value()))",
        "",
        "    def sub(self, other: Vector) -> Vector:",
        "        return self._from_value(self._client, self._client.vector_sub(self._value(), other._value()))",
        "",
        "    def dot(self, other: Vector) -> float:",
        "        return self._client.vector_dot(self._value(), other._value())",
        "",
        "    def cross(self, other: Vector) -> Vector:",
        "        return self._from_value(self._client, self._client.vector_cross(self._value(), other._value()))",
        "",
        "",
        "class Transaction:",
        "    def __init__(self, document: Document, name: str):",
        "        self._document = document",
        "        self._active = False",
        "        if not document._client.document_open_transaction(FreeCADDocumentHandle(document.value), name):",
        '            raise WasmHostError("host rejected document transaction")',
        "        self._active = True",
        "",
        "    def commit(self) -> None:",
        "        if self._active:",
        "            if not self._document._client.document_commit_transaction(",
        "                FreeCADDocumentHandle(self._document.value)",
        "            ):",
        '                raise WasmHostError("host rejected transaction commit")',
        "            self._active = False",
        "",
        "    def abort(self) -> None:",
        "        if self._active:",
        "            if not self._document._client.document_abort_transaction(",
        "                FreeCADDocumentHandle(self._document.value)",
        "            ):",
        '                raise WasmHostError("host rejected transaction abort")',
        "            self._active = False",
        "",
        "    def __enter__(self) -> Transaction:",
        "        return self",
        "",
        "    def __exit__(self, error_type, _value, _traceback) -> None:",
        "        if error_type is None:",
        "            self.commit()",
        "        else:",
        "            self.abort()",
        "",
        "",
        "class Documents:",
        "    def __init__(self, client: RawClient):",
        "        self._client = client",
        "",
        "    def create(self, name: str) -> Document:",
        "        return Document(self._client, self._client.document_new(name), owned=True)",
        "",
        "",
        "class Part:",
        "    def __init__(self, client: RawClient):",
        "        self._client = client",
        "",
        "    def make_box(self, length: float, width: float, height: float) -> TopoShape:",
        "        value = self._client.part_make_box(length, width, height)",
        "        return TopoShape(self._client, value, owned=True)",
        "",
        "",
        "class Geometry:",
        "    def __init__(self, client: RawClient):",
        "        self._client = client",
        "",
        "    def vector(self, x: float, y: float, z: float) -> Vector:",
        "        return Vector._from_value(self._client, self._client.vector_new(x, y, z))",
        "",
        "",
        "class Extension:",
        "    \"\"\"Public FreeCAD Extension API facade.\"\"\"",
        "",
        "    def __init__(self, dispatch: Callable[[bytes], bytes]):",
        "        self._raw = RawClient(dispatch)",
        "        self._documents = Documents(self._raw)",
        "        self._part = Part(self._raw)",
        "        self._geometry = Geometry(self._raw)",
        "",
        "    @property",
        "    def raw(self) -> RawClient:",
        "        return self._raw",
        "",
        "    def documents(self) -> Documents:",
        "        return self._documents",
        "",
        "    def part(self) -> Part:",
        "        return self._part",
        "",
        "    def geometry(self) -> Geometry:",
        "        return self._geometry",
        "",
    ]


def render_python(model: dict[str, Any]) -> str:
    api = model.get("api", "org.freecad.wasm.api@0")
    abi = model.get("abi", {})
    request_magic = abi.get("request_magic", "FCWA")
    request_version = int(abi.get("request_version", 1))
    class_names = dict(classes(model))
    value_names = {full_name: name for full_name, name, _ in value_types(model)}
    operations = model.get("operations", [])
    lines = [
        "# Generated by generate_wasm_sdk.py. Do not edit.",
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "from typing import Callable, NewType",
        "import struct",
        "",
        f'API_VERSION = "{api}"',
        f'API_CATALOG_SIGNATURE = "{abi.get("catalog_signature", "")}"',
        "Handle = int",
        f"REQUEST_HEADER_SIZE = {int(abi.get('request_header_size', 12))}",
        f"RESPONSE_HEADER_SIZE = {int(abi.get('response_header_size', 12))}",
        "REQUEST_CAPACITY = 512",
        "MAX_STRING_LENGTH = 128",
        "",
        "",
        "class WasmGuestError(RuntimeError):",
        "    \"\"\"Base error for Python guest transport failures.\"\"\"",
        "",
        "",
        "class WasmHostError(WasmGuestError):",
        "    \"\"\"A capability or host-side operation rejected the request.\"\"\"",
        "",
        "    def __init__(self, message: str, code: int = 6):",
        "        super().__init__(message)",
        "        self.code = code",
        "",
        "",
        "class WasmProtocolError(WasmGuestError):",
        "    \"\"\"The host returned a response that violates the WASM ABI.\"\"\"",
        "",
    ]
    for _, name in class_names.items():
        lines.append(f'{name} = NewType("{name}", int)')
    if class_names:
        lines.append("")
    for _, name, encoding in value_types(model):
        if encoding != "vector3-f64":
            raise ValueError(f"unsupported Python Wasm value encoding: {encoding}")
        lines.extend(
            [
                "@dataclass(frozen=True)",
                f"class {name}:",
                "    x: float",
                "    y: float",
                "    z: float",
                "",
            ]
        )

    lines.extend(["class operations:", ""])
    if operations:
        for operation in operations:
            constant = operation_constant_name(operation.get("name", "operation"))
            lines.append(f"    {constant} = {int(operation.get('id', 0))}")
            permission = operation.get("permission")
            if permission:
                lines.append(f'    {constant}_PERMISSION = "{permission}"')
            returns = operation.get("returns", {})
            if returns.get("kind") == "handle":
                lines.append(
                    f'    {constant}_OWNERSHIP = "{returns.get("ownership", "borrowed")}"'
                )
            if operation.get("transaction"):
                lines.append(
                    f'    {constant}_TRANSACTION = "{operation["transaction"]}"'
                )
            lines.append(
                f"    {constant}_FALLIBLE = {bool(operation.get('fallible', True))!r}"
            )
            lines.append(
                f"    {constant}_NULLABLE = {bool(operation.get('returns', {}).get('nullable', False))!r}"
            )
            lines.append(
                f"    {constant}_CONSUMES = {bool(operation.get('consumes', False))!r}"
            )
    else:
        lines.append("    pass")
    lines.extend(
        [
            "",
            "",
            "class _Request:",
            "    def __init__(self, operation: int):",
            "        self._operation = operation",
            "        self._payload = bytearray()",
            "",
            "    def push_u64(self, value: int) -> None:",
            "        self._payload.extend(struct.pack(\"<Q\", int(value)))",
            "",
            "    def push_f64(self, value: float) -> None:",
            "        self._payload.extend(struct.pack(\"<d\", float(value)))",
            "",
            "    def push_bool(self, value: bool) -> None:",
            "        self._payload.extend(struct.pack(\"<?\", value))",
            "",
            "    def push_string(self, value: str) -> None:",
            "        encoded = value.encode(\"utf-8\")",
            "        if len(encoded) > MAX_STRING_LENGTH:",
            "            raise WasmGuestError(\"string exceeds the ABI length limit\")",
            "        if b\"\\x00\" in encoded:",
            "            raise WasmGuestError(\"strings cannot contain NUL bytes\")",
            "        self._payload.extend(struct.pack(\"<I\", len(encoded)))",
            "        self._payload.extend(encoded)",
            "",
            "    def push_vector(self, value: FreeCADBaseVectorValue) -> None:",
            "        self.push_f64(value.x)",
            "        self.push_f64(value.y)",
            "        self.push_f64(value.z)",
            "",
            "    def finish(self) -> bytes:",
            "        if len(self._payload) > REQUEST_CAPACITY - REQUEST_HEADER_SIZE:",
            "            raise WasmGuestError(\"request exceeds the ABI capacity\")",
            "        return struct.pack(",
            f"            \"<4sBBHI\", b\"{request_magic}\", {request_version}, self._operation, 0, len(self._payload)",
            "        ) + bytes(self._payload)",
            "",
            "",
            "class RawClient:",
            "    \"\"\"Raw Python transport client over a host dispatch callback.\"\"\"",
            "",
            "    def __init__(self, dispatch: Callable[[bytes], bytes]):",
            "        self._dispatch = dispatch",
            "",
            "    def own(self, handle: int) -> OwnedHandle:",
            "        return OwnedHandle(self, handle)",
            "",
            "    def _response(self, request: _Request) -> bytes:",
            "        try:",
            "            response = self._dispatch(request.finish())",
            "        except WasmGuestError:",
            "            raise",
            "        except Exception as error:",
            "            raise WasmHostError(str(error)) from error",
            "        if not isinstance(response, (bytes, bytearray, memoryview)):",
            "            raise WasmProtocolError(\"host dispatch did not return bytes\")",
            "        response = bytes(response)",
            "        if len(response) < RESPONSE_HEADER_SIZE:",
            "            raise WasmProtocolError(\"host returned a truncated response envelope\")",
            "        magic, version, status, error_code, flags, payload_length = struct.unpack_from(\"<4sBBBBI\", response)",
            "        if magic != b\"FCWR\" or version != 1 or flags != 0:",
            "            raise WasmProtocolError(\"host returned an invalid response envelope\")",
            "        if payload_length != len(response) - RESPONSE_HEADER_SIZE:",
            "            raise WasmProtocolError(\"host returned an invalid response length\")",
            "        payload = response[RESPONSE_HEADER_SIZE:]",
            "        if status == 1:",
            "            raise WasmHostError(payload.decode(\"utf-8\", errors=\"replace\"), error_code)",
            "        if status != 0 or error_code != 0:",
            "            raise WasmProtocolError(\"host returned an invalid response status\")",
            "        return payload",
            "",
            "    def _call_handle(self, request: _Request) -> int:",
            "        response = self._response(request)",
            "        if len(response) != 8:",
            "            raise WasmProtocolError(\"host returned an invalid handle response\")",
            "        value = struct.unpack(\"<Q\", response)[0]",
            "        if value == 0:",
            "            raise WasmProtocolError(\"host returned an invalid handle response\")",
            "        return value",
            "",
            "    def _call_value(self, request: _Request) -> FreeCADBaseVectorValue:",
            "        response = self._response(request)",
            "        if len(response) != 24:",
            "            raise WasmProtocolError(\"host returned an invalid vector response\")",
            "        return FreeCADBaseVectorValue(*struct.unpack(\"<ddd\", response))",
            "",
            "    def _call_f64(self, request: _Request) -> float:",
            "        response = self._response(request)",
            "        if len(response) != 8:",
            "            raise WasmProtocolError(\"host returned an invalid f64 response\")",
            "        return struct.unpack(\"<d\", response)[0]",
            "",
            "    def _call_bool(self, request: _Request) -> bool:",
            "        response = self._response(request)",
            "        if len(response) != 1 or response[0] not in (0, 1):",
            "            raise WasmProtocolError(\"host returned an invalid boolean response\")",
            "        return bool(response[0])",
            "",
            "    def _call_empty(self, request: _Request) -> None:",
            "        response = self._response(request)",
            "        if response:",
            '            raise WasmProtocolError("host returned a non-empty response for a void operation")',
            "        return None",
            "",
            "    def _call_string(self, request: _Request) -> str:",
            "        response = self._response(request)",
            "        if len(response) < 4:",
            "            raise WasmProtocolError(\"host returned an invalid string response\")",
            "        length = struct.unpack_from(\"<I\", response)[0]",
            "        if length != len(response) - 4:",
            "            raise WasmProtocolError(\"host returned an invalid string length\")",
            "        try:",
            "            return response[4:].decode(\"utf-8\")",
            "        except UnicodeDecodeError as error:",
            "            raise WasmProtocolError(\"host returned invalid UTF-8\") from error",
            "",
            "    def _call_release(self, request: _Request) -> bool:",
            "        response = self._response(request)",
            "        if response:",
            "            raise WasmProtocolError(\"host returned a non-empty release response\")",
            "        return True",
        ]
    )

    def python_parameter_type(parameter: dict[str, Any]) -> str:
        parameter_type = parameter.get("type", {})
        kind = parameter_type.get("kind")
        if kind == "string":
            return "str"
        if kind == "float64":
            return "float"
        if kind == "bool":
            return "bool"
        if kind == "value":
            return value_names[parameter_type["type"]]
        if kind == "handle":
            full_name = parameter_type.get("type")
            return "Handle" if full_name == "Wasm.Handle" else class_names[full_name]
        raise ValueError(f"unsupported Python parameter type: {kind}")

    for operation in operations:
        name = operation.get("name", "operation")
        method = rust_method_name(name)
        params = operation.get("params", [])
        return_type = operation.get("returns", {})
        return_kind = return_type.get("kind")
        if return_kind == "handle":
            result_type = return_type.get("type")
            result_name = "Handle" if result_type == "Wasm.Handle" else class_names[result_type]
            result_signature = result_name
        elif return_kind == "value":
            result_signature = value_names[return_type["type"]]
        elif return_kind == "float64":
            result_signature = "float"
        elif return_kind == "string":
            result_signature = "str"
        elif return_kind == "bool":
            result_signature = "bool"
        elif return_kind == "none":
            result_signature = "None"
        else:
            raise ValueError(f"unsupported Python return type: {return_kind}")

        parameter_declarations = [
            f"{parameter.get('name', 'value')}: {python_parameter_type(parameter)}"
            for parameter in params
        ]
        signature = ", ".join(["self", *parameter_declarations])
        lines.extend(
            [
                f"    def {method}({signature}) -> {result_signature}:",
                f'        \"\"\"Call {operation.get("wire_name", name)}.\"\"\"',
                f"        request = _Request(operations.{operation_constant_name(name)})",
            ]
        )
        for parameter in params:
            parameter_name = parameter.get("name", "value")
            kind = parameter.get("type", {}).get("kind")
            if kind == "string":
                lines.append(f"        request.push_string({parameter_name})")
            elif kind == "float64":
                lines.append(f"        request.push_f64({parameter_name})")
            elif kind == "bool":
                lines.append(f"        request.push_bool({parameter_name})")
            elif kind == "value":
                lines.append(f"        request.push_vector({parameter_name})")
            elif kind == "handle":
                lines.append(f"        request.push_u64(int({parameter_name}))")
            else:
                raise ValueError(f"unsupported Python parameter type: {kind}")

        if return_kind == "handle":
            lines.extend(
                [
                    "        value = self._call_handle(request)",
                    f"        return {result_name}(value)",
                    "",
                ]
            )
        elif return_kind == "value":
            lines.extend(["        return self._call_value(request)", ""])
        elif return_kind == "float64":
            lines.extend(["        return self._call_f64(request)", ""])
        elif return_kind == "string":
            lines.extend(["        return self._call_string(request)", ""])
        elif return_kind == "bool" and name == "release":
            lines.extend(["        return self._call_release(request)", ""])
        elif return_kind == "bool":
            lines.extend(["        return self._call_bool(request)", ""])
        elif return_kind == "none":
            lines.extend(["        return self._call_empty(request)", ""])

    lines.extend(
        [
            "",
            "",
            "Client = RawClient",
            "",
            "",
            "class OwnedHandle:",
            "    \"\"\"Explicitly owned guest handle with deterministic release.\"\"\"",
            "",
            "    def __init__(self, client: RawClient, value: int):",
            "        self._client = client",
            "        self.value = int(value)",
            "        self._closed = False",
            "",
            "    def close(self) -> None:",
            "        if not self._closed:",
            "            self._client.release(self.value)",
            "            self._closed = True",
            "",
            "    def __enter__(self) -> int:",
            "        return self.value",
            "",
            "    def __exit__(self, _type, _value, _traceback) -> None:",
            "        self.close()",
            "",
        ]
    )
    if has_extension_facade(model):
        lines.extend(_python_extension_facade())
    return "\n".join(lines)


def _rust_extension_facade() -> list[str]:
    """Render the public Rust facade over the generated raw client."""

    return [
        "",
        "",
        "#[derive(Clone, Copy)]",
        "pub struct Extension",
        "{",
        "    raw: RawClient,",
        "}",
        "",
        "impl Extension",
        "{",
        "    pub const fn new() -> Self",
        "    {",
        "        Self { raw: RawClient::new() }",
        "    }",
        "",
        "    pub const fn raw(&self) -> RawClient",
        "    {",
        "        self.raw",
        "    }",
        "",
        "    pub const fn documents(&self) -> Documents",
        "    {",
        "        Documents { raw: self.raw }",
        "    }",
        "",
        "    pub const fn part(&self) -> Part",
        "    {",
        "        Part { raw: self.raw }",
        "    }",
        "",
        "    pub const fn geometry(&self) -> Geometry",
        "    {",
        "        Geometry { raw: self.raw }",
        "    }",
        "}",
        "",
        "#[derive(Clone, Copy)]",
        "pub struct Documents",
        "{",
        "    raw: RawClient,",
        "}",
        "",
        "impl Documents",
        "{",
        "    pub fn create(&self, name: &[u8]) -> Result<Document>",
        "    {",
        "        self.raw.document_new(name).map(|handle| Document {",
        "            raw: self.raw,",
        "            handle,",
        "            owned: true,",
        "        })",
        "    }",
        "}",
        "",
        "pub struct Document",
        "{",
        "    raw: RawClient,",
        "    handle: FreeCADDocumentHandle,",
        "    owned: bool,",
        "}",
        "",
        "impl Document",
        "{",
        "    pub fn is_saved(&self) -> Result<bool>",
        "    {",
        "        self.raw.document_is_saved(self.handle)",
        "    }",
        "",
        "    pub fn get_object(&self, name: &[u8]) -> Result<DocumentObject>",
        "    {",
        "        self.raw.document_get_object(self.handle, name).map(|handle| DocumentObject {",
        "            raw: self.raw,",
        "            handle,",
        "            owned: true,",
        "        })",
        "    }",
        "",
        "    pub fn add_object(&self, shape: &TopoShape, name: &[u8]) -> Result<DocumentObject>",
        "    {",
        "        self.raw.document_add_object(self.handle, shape.handle, name).map(|handle| DocumentObject {",
        "            raw: self.raw,",
        "            handle,",
        "            owned: true,",
        "        })",
        "    }",
        "",
        "    pub fn transaction(&self, name: &[u8]) -> Result<Transaction>",
        "    {",
        "        if !self.raw.document_open_transaction(self.handle, name)? {",
        "            return Err(Error { code: ErrorCode::HostFailure });",
        "        }",
        "        Ok(Transaction { raw: self.raw, handle: self.handle, active: true })",
        "    }",
        "}",
        "",
        "impl Drop for Document",
        "{",
        "    fn drop(&mut self)",
        "    {",
        "        if self.owned {",
        "            let _ = self.raw.release(self.handle.0);",
        "        }",
        "    }",
        "}",
        "",
        "pub struct DocumentObject",
        "{",
        "    raw: RawClient,",
        "    handle: FreeCADDocumentObjectHandle,",
        "    owned: bool,",
        "}",
        "",
        "impl DocumentObject",
        "{",
        "    pub fn label(&self, output: &mut [u8]) -> Result<usize>",
        "    {",
        "        self.raw.document_object_get_label(self.handle, output)",
        "    }",
        "",
        "    pub fn set_label(&self, label: &[u8]) -> Result<()>",
        "    {",
        "        self.raw.document_object_set_label(self.handle, label)",
        "    }",
        "}",
        "",
        "impl Drop for DocumentObject",
        "{",
        "    fn drop(&mut self)",
        "    {",
        "        if self.owned {",
        "            let _ = self.raw.release(self.handle.0);",
        "        }",
        "    }",
        "}",
        "",
        "pub struct TopoShape",
        "{",
        "    raw: RawClient,",
        "    handle: PartTopoShapeHandle,",
        "    owned: bool,",
        "}",
        "",
        "impl TopoShape",
        "{",
        "    pub fn is_null(&self) -> Result<bool>",
        "    {",
        "        self.raw.topo_shape_is_null(self.handle)",
        "    }",
        "",
        "    pub fn is_valid(&self) -> Result<bool>",
        "    {",
        "        self.raw.topo_shape_is_valid(self.handle)",
        "    }",
        "",
        "    pub fn length(&self) -> Result<f64>",
        "    {",
        "        self.raw.topo_shape_length(self.handle)",
        "    }",
        "",
        "    pub fn area(&self) -> Result<f64>",
        "    {",
        "        self.raw.topo_shape_area(self.handle)",
        "    }",
        "",
        "    pub fn volume(&self) -> Result<f64>",
        "    {",
        "        self.raw.topo_shape_volume(self.handle)",
        "    }",
        "}",
        "",
        "impl Drop for TopoShape",
        "{",
        "    fn drop(&mut self)",
        "    {",
        "        if self.owned {",
        "            let _ = self.raw.release(self.handle.0);",
        "        }",
        "    }",
        "}",
        "",
        "pub struct Transaction",
        "{",
        "    raw: RawClient,",
        "    handle: FreeCADDocumentHandle,",
        "    active: bool,",
        "}",
        "",
        "impl Transaction",
        "{",
        "    pub fn commit(&mut self) -> Result<()> ",
        "    {",
        "        if self.active && !self.raw.document_commit_transaction(self.handle)? {",
        "            return Err(Error { code: ErrorCode::HostFailure });",
        "        }",
        "        self.active = false;",
        "        Ok(())",
        "    }",
        "",
        "    pub fn abort(&mut self) -> Result<()> ",
        "    {",
        "        if self.active && !self.raw.document_abort_transaction(self.handle)? {",
        "            return Err(Error { code: ErrorCode::HostFailure });",
        "        }",
        "        self.active = false;",
        "        Ok(())",
        "    }",
        "}",
        "",
        "impl Drop for Transaction",
        "{",
        "    fn drop(&mut self)",
        "    {",
        "        if self.active {",
        "            let _ = self.raw.document_abort_transaction(self.handle);",
        "        }",
        "    }",
        "}",
        "",
        "#[derive(Clone, Copy)]",
        "pub struct Part",
        "{",
        "    raw: RawClient,",
        "}",
        "",
        "impl Part",
        "{",
        "    pub fn make_box(&self, length: f64, width: f64, height: f64) -> Result<TopoShape>",
        "    {",
        "        self.raw.part_make_box(length, width, height).map(|handle| TopoShape {",
        "            raw: self.raw,",
        "            handle,",
        "            owned: true,",
        "        })",
        "    }",
        "}",
        "",
        "pub struct Vector",
        "{",
        "    raw: RawClient,",
        "    value: FreeCADBaseVectorValue,",
        "}",
        "",
        "impl Vector",
        "{",
        "    pub fn x(&self) -> f64 { self.value.x }",
        "    pub fn y(&self) -> f64 { self.value.y }",
        "    pub fn z(&self) -> f64 { self.value.z }",
        "",
        "    pub fn add(&self, other: &Vector) -> Result<Vector>",
        "    {",
        "        self.raw.vector_add(self.value, other.value).map(|value| Vector { raw: self.raw, value })",
        "    }",
        "",
        "    pub fn sub(&self, other: &Vector) -> Result<Vector>",
        "    {",
        "        self.raw.vector_sub(self.value, other.value).map(|value| Vector { raw: self.raw, value })",
        "    }",
        "",
        "    pub fn dot(&self, other: &Vector) -> Result<f64>",
        "    {",
        "        self.raw.vector_dot(self.value, other.value)",
        "    }",
        "",
        "    pub fn cross(&self, other: &Vector) -> Result<Vector>",
        "    {",
        "        self.raw.vector_cross(self.value, other.value).map(|value| Vector { raw: self.raw, value })",
        "    }",
        "}",
        "",
        "#[derive(Clone, Copy)]",
        "pub struct Geometry",
        "{",
        "    raw: RawClient,",
        "}",
        "",
        "impl Geometry",
        "{",
        "    pub fn vector(&self, x: f64, y: f64, z: f64) -> Result<Vector>",
        "    {",
        "        self.raw.vector_new(x, y, z).map(|value| Vector { raw: self.raw, value })",
        "    }",
        "}",
        "",
    ]


def render_rust(model: dict[str, Any]) -> str:
    api = model.get("api", "org.freecad.wasm.api@0")
    abi = model.get("abi", {})
    request_magic = abi.get("request_magic", "FCWA")
    request_version = int(abi.get("request_version", 1))
    error_codes = abi.get("error_codes", {})

    def error_code(name: str, default: int) -> int:
        return int(error_codes.get(name, default))
    class_names = dict(classes(model))
    value_names = {full_name: name for full_name, name, _ in value_types(model)}
    lines = [
        "// Generated by generate_wasm_sdk.py. Do not edit.",
        "",
        "use core::ptr;",
        "",
        "#[link(wasm_import_module = \"freecad\")]",
        "unsafe extern \"C\" {",
        "    fn freecad_alloc(size: u32) -> u32;",
        "    fn freecad_dispatch(request: *const u8, request_length: u32) -> u64;",
        "    fn freecad_release(response_address: u32);",
        "}",
        "",
        "#[allow(dead_code)]",
        f'pub const API_VERSION: &str = "{api}";',
        f'pub const API_CATALOG_SIGNATURE: &str = "{abi.get("catalog_signature", "")}";',
        "pub type Handle = u64;",
        "",
    ]
    for _, name, encoding in value_types(model):
        if encoding != "vector3-f64":
            raise ValueError(f"unsupported Rust Wasm value encoding: {encoding}")
        lines.extend(
            [
                "#[repr(C)]",
                "#[derive(Clone, Copy, Debug, PartialEq)]",
                f"pub struct {name}",
                "{",
                "    pub x: f64,",
                "    pub y: f64,",
                "    pub z: f64,",
                "}",
                "",
            ]
        )
    for _, name in classes(model):
        lines.extend(
            [
                "#[repr(transparent)]",
                "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
                f"pub struct {name}(pub Handle);",
                "",
            ]
        )
    operations = model.get("operations", [])
    if operations:
        lines.extend(["#[allow(dead_code)]", "pub mod operations {", ""])
        for operation in operations:
            constant = re.sub(
                r"[^A-Za-z0-9]+",
                "_",
                re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", operation.get("name", "operation")),
            ).upper()
            lines.append(f"    pub const {constant}: u8 = {int(operation.get('id', 0))};")
            permission = operation.get("permission")
            if permission:
                lines.append(
                    f'    pub const {constant}_PERMISSION: &str = "{permission}";'
                )
            returns = operation.get("returns", {})
            if returns.get("kind") == "handle":
                lines.append(
                    f'    pub const {constant}_OWNERSHIP: &str = "{returns.get("ownership", "borrowed")}";'
                )
            if operation.get("transaction"):
                lines.append(
                    f'    pub const {constant}_TRANSACTION: &str = "{operation["transaction"]}";'
                )
            lines.append(
                f"    pub const {constant}_FALLIBLE: bool = {'true' if operation.get('fallible', True) else 'false'};"
            )
            lines.append(
                f"    pub const {constant}_NULLABLE: bool = {'true' if operation.get('returns', {}).get('nullable', False) else 'false'};"
            )
            lines.append(
                f"    pub const {constant}_CONSUMES: bool = {'true' if operation.get('consumes', False) else 'false'};"
            )
        lines.extend(["", "}", ""])

    lines.extend(
        [
            f"const REQUEST_HEADER_SIZE: usize = {int(abi.get('request_header_size', 12))};",
            f"const RESPONSE_HEADER_SIZE: usize = {int(abi.get('response_header_size', 12))};",
            "const REQUEST_CAPACITY: usize = 512;",
            "const MAX_STRING_LENGTH: usize = 128;",
            "",
            "struct Request",
            "{",
            "    bytes: [u8; REQUEST_CAPACITY],",
            "    length: usize,",
            "}",
            "",
            "impl Request",
            "{",
            "    fn new(operation: u8, payload_length: usize) -> Option<Self>",
            "    {",
            "        if payload_length > REQUEST_CAPACITY - REQUEST_HEADER_SIZE",
            "            || payload_length > u32::MAX as usize",
            "        {",
            "            return None;",
            "        }",
            "        let mut request = Self {",
            "            bytes: [0; REQUEST_CAPACITY],",
            "            length: REQUEST_HEADER_SIZE,",
            "        };",
            f"        request.bytes[0..4].copy_from_slice(b\"{request_magic}\");",
            f"        request.bytes[4] = {request_version};",
            "        request.bytes[5] = operation;",
            "        request.bytes[8..12].copy_from_slice(&(payload_length as u32).to_le_bytes());",
            "        Some(request)",
            "    }",
            "",
            "    fn push_bytes(&mut self, bytes: &[u8]) -> Option<()>",
            "    {",
            "        let end = self.length.checked_add(bytes.len())?;",
            "        if end > REQUEST_CAPACITY {",
            "            return None;",
            "        }",
            "        self.bytes[self.length..end].copy_from_slice(bytes);",
            "        self.length = end;",
            "        Some(())",
            "    }",
            "",
            "    #[allow(dead_code)]",
            "    fn push_u8(&mut self, value: u8) -> Option<()>",
            "    {",
            "        self.push_bytes(&[value])",
            "    }",
            "",
            "    fn push_u32(&mut self, value: u32) -> Option<()>",
            "    {",
            "        self.push_bytes(&value.to_le_bytes())",
            "    }",
            "",
            "    fn push_u64(&mut self, value: u64) -> Option<()>",
            "    {",
            "        self.push_bytes(&value.to_le_bytes())",
            "    }",
            "",
            "    fn push_f64(&mut self, value: f64) -> Option<()>",
            "    {",
            "        self.push_u64(value.to_bits())",
            "    }",
            "",
            "    fn push_string(&mut self, value: &[u8]) -> Option<()>",
            "    {",
            "        if value.len() > MAX_STRING_LENGTH {",
            "            return None;",
            "        }",
            "        self.push_u32(value.len() as u32)?;",
            "        self.push_bytes(value)",
            "    }",
            "",
            "    fn push_vector(&mut self, value: FreeCADBaseVectorValue) -> Option<()>",
            "    {",
            "        self.push_f64(value.x)?;",
            "        self.push_f64(value.y)?;",
            "        self.push_f64(value.z)",
            "    }",
            "}",
            "",
            "#[allow(dead_code)]",
            "#[repr(u8)]",
            "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
            "pub enum ErrorCode",
            "{",
            f"    None = {error_code('none', 0)},",
            f"    InvalidRequest = {error_code('invalid_request', 1)},",
            f"    PermissionDenied = {error_code('permission_denied', 2)},",
            f"    InvalidHandle = {error_code('invalid_handle', 3)},",
            f"    Unsupported = {error_code('unsupported', 4)},",
            f"    LimitExceeded = {error_code('limit_exceeded', 5)},",
            f"    HostFailure = {error_code('host_failure', 6)},",
            f"    Protocol = {error_code('protocol', 7)},",
            "}",
            "",
            "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
            "pub struct Error { pub code: ErrorCode }",
            "",
            "impl Error",
            "{",
            "    const fn protocol() -> Self { Self { code: ErrorCode::Protocol } }",
            "}",
            "",
            "pub type Result<T> = core::result::Result<T, Error>;",
            "",
            "#[derive(Clone, Copy, Debug, Default)]",
            "pub struct RawClient;",
            "",
            "#[allow(dead_code)]",
            "pub struct OwnedHandle",
            "{",
            "    client: RawClient,",
            "    value: Handle,",
            "    closed: bool,",
            "}",
            "",
            "#[allow(dead_code)]",
            "impl OwnedHandle",
            "{",
            "    pub fn value(&self) -> Handle { self.value }",
            "",
            "    pub fn close(&mut self) -> Result<()> ",
            "    {",
            "        if self.closed { return Ok(()); }",
            "        self.client.release(self.value).map(|_| ())?;",
            "        self.closed = true;",
            "        Ok(())",
            "    }",
            "}",
            "",
            "#[allow(dead_code)]",
            "impl RawClient",
            "{",
            "    pub const fn new() -> Self",
            "    {",
            "        Self",
            "    }",
            "",
            "    pub fn own(&self, value: Handle) -> OwnedHandle",
            "    {",
            "        OwnedHandle { client: *self, value, closed: false }",
            "    }",
            "",
            "    pub fn allocate_response(&self, size: u32) -> u32",
            "    {",
            "        unsafe { freecad_alloc(size) }",
            "    }",
            "",
            "    fn release_response(address: u32)",
            "    {",
            "        if address != 0 {",
            "            unsafe { freecad_release(address); }",
            "        }",
            "    }",
            "",
            "    fn response(&self, request: &Request) -> Result<(u32, u32, u32)>",
            "    {",
            "        let response = unsafe { freecad_dispatch(request.bytes.as_ptr(), request.length as u32) };",
            "        let address = response as u32;",
            "        let length = (response >> 32) as u32;",
            "        if address == 0 || length < RESPONSE_HEADER_SIZE as u32 {",
            "            Self::release_response(address);",
            "            return Err(Error::protocol());",
            "        }",
            "        let bytes = address as *const u8;",
            "        let mut payload_length = 0u32;",
            "        unsafe {",
            "            if *bytes.add(0) != b'F' || *bytes.add(1) != b'C' || *bytes.add(2) != b'W' || *bytes.add(3) != b'R' || *bytes.add(4) != 1 || *bytes.add(7) != 0 {",
            "                Self::release_response(address);",
            "                return Err(Error::protocol());",
            "            }",
            "            for shift in 0..4 { payload_length |= (*bytes.add(8 + shift) as u32) << (shift * 8); }",
            "            if payload_length != length - RESPONSE_HEADER_SIZE as u32 {",
            "                Self::release_response(address);",
            "                return Err(Error::protocol());",
            "            }",
            "            if *bytes.add(5) == 1 {",
            "                let code = match *bytes.add(6) {",
            "                    1 => ErrorCode::InvalidRequest,",
            "                    2 => ErrorCode::PermissionDenied,",
            "                    3 => ErrorCode::InvalidHandle,",
            "                    4 => ErrorCode::Unsupported,",
            "                    5 => ErrorCode::LimitExceeded,",
            "                    6 => ErrorCode::HostFailure,",
            "                    7 => ErrorCode::Protocol,",
            "                    _ => ErrorCode::Protocol,",
            "                };",
            "                Self::release_response(address);",
            "                return Err(Error { code });",
            "            }",
            "            if *bytes.add(5) != 0 || *bytes.add(6) != 0 {",
            "                Self::release_response(address);",
            "                return Err(Error::protocol());",
            "            }",
            "        }",
            "        Ok((address, address + RESPONSE_HEADER_SIZE as u32, payload_length))",
            "    }",
            "",
            "    fn call_handle(&self, request: &Request) -> Result<Handle>",
            "    {",
            "        let (address, payload, length) = self.response(request)?;",
            "        if length != 8 { Self::release_response(address); return Err(Error::protocol()); }",
            "        let mut bytes = [0u8; 8];",
            "        unsafe { ptr::copy_nonoverlapping(payload as *const u8, bytes.as_mut_ptr(), bytes.len()); }",
            "        Self::release_response(address);",
            "        let value = u64::from_le_bytes(bytes);",
            "        if value == 0 { Err(Error::protocol()) } else { Ok(value) }",
            "    }",
            "",
            "    fn call_value(&self, request: &Request) -> Result<FreeCADBaseVectorValue>",
            "    {",
            "        let (address, payload, length) = self.response(request)?;",
            "        if length != 24 { Self::release_response(address); return Err(Error::protocol()); }",
            "        let mut bytes = [0u8; 24];",
            "        unsafe {",
            "            ptr::copy_nonoverlapping(payload as *const u8, bytes.as_mut_ptr(), bytes.len());",
            "        }",
            "        Self::release_response(address);",
            "        Ok(FreeCADBaseVectorValue {",
            "            x: f64::from_bits(u64::from_le_bytes(bytes[0..8].try_into().map_err(|_| Error::protocol())?)),",
            "            y: f64::from_bits(u64::from_le_bytes(bytes[8..16].try_into().map_err(|_| Error::protocol())?)),",
            "            z: f64::from_bits(u64::from_le_bytes(bytes[16..24].try_into().map_err(|_| Error::protocol())?)),",
            "        })",
            "    }",
            "",
            "    fn call_f64(&self, request: &Request) -> Result<f64>",
            "    {",
            "        let (address, payload, length) = self.response(request)?;",
            "        if length != 8 { Self::release_response(address); return Err(Error::protocol()); }",
            "        let mut bytes = [0u8; 8];",
            "        unsafe {",
            "            ptr::copy_nonoverlapping(payload as *const u8, bytes.as_mut_ptr(), bytes.len());",
            "        }",
            "        Self::release_response(address);",
            "        Ok(f64::from_bits(u64::from_le_bytes(bytes)))",
            "    }",
            "",
            "    fn call_bool(&self, request: &Request) -> Result<bool>",
            "    {",
            "        let (address, payload, length) = self.response(request)?;",
            "        if length != 1 { Self::release_response(address); return Err(Error::protocol()); }",
            "        let value = unsafe { *(payload as *const u8) };",
            "        Self::release_response(address);",
            "        match value {",
            "            0 => Ok(false),",
            "            1 => Ok(true),",
            "            _ => Err(Error::protocol()),",
            "        }",
            "    }",
            "",
            "    fn call_empty(&self, request: &Request) -> Result<()> ",
            "    {",
            "        let (address, _payload, length) = self.response(request)?;",
            "        if length != 0 { Self::release_response(address); return Err(Error::protocol()); }",
            "        Self::release_response(address);",
            "        Ok(())",
            "    }",
            "",
            "    fn call_string(&self, request: &Request, output: &mut [u8]) -> Result<usize>",
            "    {",
            "        let (address, payload, length) = self.response(request)?;",
            "        if length < 4 { Self::release_response(address); return Err(Error::protocol()); }",
            "        let bytes = payload as *const u8;",
            "        let mut value_length = 0u32;",
            "        unsafe {",
            "            for shift in 0..4 {",
            "                value_length |= (*bytes.add(shift) as u32) << (shift * 8);",
            "            }",
            "        }",
            "        if value_length != length - 4 || value_length as usize > output.len() {",
            "            Self::release_response(address);",
            "            return Err(Error::protocol());",
            "        }",
            "        unsafe {",
            "            ptr::copy_nonoverlapping(bytes.add(4), output.as_mut_ptr(), value_length as usize);",
            "        }",
            "        Self::release_response(address);",
            "        Ok(value_length as usize)",
            "    }",
            "",
        ]
    )

    def rust_parameter_type(parameter: dict[str, Any]) -> str:
        parameter_type = parameter.get("type", {})
        kind = parameter_type.get("kind")
        if kind == "string":
            return "&[u8]"
        if kind == "float64":
            return "f64"
        if kind == "bool":
            return "bool"
        if kind == "value":
            return value_names[parameter_type["type"]]
        if kind == "handle":
            full_name = parameter_type.get("type")
            return "Handle" if full_name == "Wasm.Handle" else class_names[full_name]
        raise ValueError(f"unsupported Rust parameter type: {kind}")

    def payload_size_expression(params: list[dict[str, Any]]) -> str:
        sizes = []
        for parameter in params:
            parameter_type = parameter.get("type", {})
            kind = parameter_type.get("kind")
            if kind == "string":
                sizes.append(f"4usize + {parameter.get('name', 'value')}.len()")
            elif kind in {"float64", "handle"}:
                sizes.append("8usize")
            elif kind == "bool":
                sizes.append("1usize")
            elif kind == "value":
                sizes.append("24usize")
            else:
                raise ValueError(f"unsupported Rust payload type: {kind}")
        return " + ".join(sizes) if sizes else "0usize"

    def append_parameter(parameter: dict[str, Any]) -> list[str]:
        parameter_type = parameter.get("type", {})
        kind = parameter_type.get("kind")
        name = parameter.get("name", "value")
        if kind == "string":
            return [f"        request.push_string({name}).ok_or(Error::protocol())?;"]
        if kind == "float64":
            return [f"        request.push_f64({name}).ok_or(Error::protocol())?;"]
        if kind == "bool":
            return [f"        request.push_u8({name} as u8).ok_or(Error::protocol())?;"]
        if kind == "value":
            if parameter_type.get("encoding") != "vector3-f64":
                raise ValueError(
                    f"unsupported Rust Wasm value encoding: {parameter_type.get('encoding')}"
                )
            return [f"        request.push_vector({name}).ok_or(Error::protocol())?;"]
        if kind == "handle":
            value = name if parameter_type.get("type") == "Wasm.Handle" else f"{name}.0"
            return [f"        request.push_u64({value}).ok_or(Error::protocol())?;"]
        raise ValueError(f"unsupported Rust parameter type: {kind}")

    for operation in operations:
        name = operation.get("name", "operation")
        method = rust_method_name(name)
        params = operation.get("params", [])
        return_type = operation.get("returns", {})
        return_kind = return_type.get("kind")
        if return_kind == "handle":
            result_type = return_type.get("type")
            result_name = "Handle" if result_type == "Wasm.Handle" else class_names[result_type]
            result_signature = f"Result<{result_name}>"
        elif return_kind == "value":
            result_signature = "Result<{}>".format(value_names[return_type["type"]])
        elif return_kind == "float64":
            result_signature = "Result<f64>"
        elif return_kind == "string":
            result_signature = "Result<usize>"
        elif return_kind == "bool":
            result_signature = "Result<bool>"
        elif return_kind == "none":
            result_signature = "Result<()>"
        else:
            raise ValueError(f"unsupported Rust return type: {return_kind}")
        declarations = [
            f"{parameter.get('name', 'value')}: {rust_parameter_type(parameter)}"
            for parameter in params
        ]
        if return_kind == "string":
            declarations.append("output: &mut [u8]")
        signature = ", ".join(["&self", *declarations])
        lines.append(f"    pub fn {method}({signature}) -> {result_signature}")
        lines.extend(["    {"])
        if any(parameter.get("type", {}).get("kind") == "string" for parameter in params):
            for parameter in params:
                if parameter.get("type", {}).get("kind") == "string":
                    lines.append(
                        f"        if {parameter.get('name', 'value')}.len() > MAX_STRING_LENGTH {{"
                    )
                    lines.append("            return Err(Error::protocol());")
                    lines.append("        }")
        operation_constant = re.sub(
            r"[^A-Za-z0-9]+",
            "_",
            re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name),
        ).upper()
        lines.append(
            f"        let mut request = Request::new(operations::{operation_constant}, "
            f"{payload_size_expression(params)}).ok_or(Error::protocol())?;"
        )
        for parameter in params:
            lines.extend(append_parameter(parameter))
        if return_kind == "handle":
            lines.extend(
                [
                    f"        self.call_handle(&request).map({result_name})",
                    "    }",
                    "",
                ]
            )
        elif return_kind == "value":
            lines.extend(["        self.call_value(&request)", "    }", ""])
        elif return_kind == "float64":
            lines.extend(["        self.call_f64(&request)", "    }", ""])
        elif return_kind == "string":
            lines.extend(["        self.call_string(&request, output)", "    }", ""])
        elif return_kind == "bool" and name == "release":
            lines.extend(
                [
                    "        self.call_empty(&request).map(|_| true)",
                    "    }",
                    "",
                ]
            )
        elif return_kind == "bool":
            lines.extend(["        self.call_bool(&request)", "    }", ""])
        elif return_kind == "none":
            lines.extend(["        self.call_empty(&request)", "    }", ""])
        else:
            raise ValueError(f"unsupported Rust return type: {return_type.get('kind')}")

    lines.extend(
        [
            "}",
            "",
            "pub type Client = RawClient;",
            "",
        ]
    )
    if has_extension_facade(model):
        lines.extend(_rust_extension_facade())
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--api-json", required=True, type=Path)
    parser.add_argument("--cpp-output", required=True, type=Path)
    parser.add_argument("--rust-output", required=True, type=Path)
    parser.add_argument("--python-output", required=True, type=Path)
    args = parser.parse_args()

    model = json.loads(args.api_json.read_text(encoding="utf-8"))
    args.cpp_output.parent.mkdir(parents=True, exist_ok=True)
    args.rust_output.parent.mkdir(parents=True, exist_ok=True)
    args.python_output.parent.mkdir(parents=True, exist_ok=True)
    args.cpp_output.write_text(render_cpp(model), encoding="utf-8")
    args.rust_output.write_text(render_rust(model), encoding="utf-8")
    args.python_output.write_text(render_python(model), encoding="utf-8")


if __name__ == "__main__":
    main()
