#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-2.1-or-later

"""Generate typed Rust and C++ guest layers from the WASM API model."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
from typing import Any


CPP_KEYWORDS = {
    "class",
    "const",
    "enum",
    "explicit",
    "namespace",
    "struct",
    "template",
    "typename",
}
RUST_KEYWORDS = {
    "as",
    "crate",
    "enum",
    "extern",
    "fn",
    "impl",
    "in",
    "let",
    "match",
    "mod",
    "pub",
    "ref",
    "self",
    "struct",
    "trait",
    "type",
    "use",
}


def type_name(full_name: str, keywords: set[str]) -> str:
    parts = re.findall(r"[A-Za-z0-9]+", full_name)
    name = "".join(part[:1].upper() + part[1:] for part in parts) or "ApiType"
    if name[0].isdigit():
        name = f"Type{name}"
    if name.lower() in keywords:
        name += "Type"
    return f"{name}Handle"


def value_type_name(full_name: str, keywords: set[str]) -> str:
    handle_name = type_name(full_name, keywords)
    return f"{handle_name[:-len('Handle')]}Value"


def rust_method_name(name: str) -> str:
    return re.sub(
        r"[^a-zA-Z0-9]+",
        "_",
        re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name),
    ).lower()


def classes(model: dict[str, Any]) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    seen: set[str] = set()

    def add(full_name: str) -> None:
        if (
            not isinstance(full_name, str)
            or not full_name
            or full_name == "Wasm.Handle"
            or full_name in seen
        ):
            return
        seen.add(full_name)
        entries.append((full_name, type_name(full_name, CPP_KEYWORDS | RUST_KEYWORDS)))

    for api_class in model.get("classes", []):
        if api_class.get("representation", {}).get("kind") != "value":
            add(api_class.get("full_name"))
    for operation in model.get("operations", []):
        for parameter in operation.get("params", []):
            type_model = parameter.get("type", {})
            if type_model.get("kind") == "handle":
                add(type_model.get("type"))
        return_type = operation.get("returns", {})
        if return_type.get("kind") == "handle":
            add(return_type.get("type"))
    return entries


def value_types(model: dict[str, Any]) -> list[tuple[str, str, str]]:
    entries: list[tuple[str, str, str]] = []
    seen: set[str] = set()

    def add(full_name: str, encoding: str) -> None:
        if (
            not isinstance(full_name, str)
            or not full_name
            or full_name in seen
        ):
            return
        seen.add(full_name)
        entries.append(
            (
                full_name,
                value_type_name(full_name, CPP_KEYWORDS | RUST_KEYWORDS),
                encoding,
            )
        )

    for api_class in model.get("classes", []):
        representation = api_class.get("representation", {})
        if representation.get("kind") == "value":
            add(api_class.get("full_name"), representation.get("encoding", ""))
    for operation in model.get("operations", []):
        for parameter in operation.get("params", []):
            type_model = parameter.get("type", {})
            if type_model.get("kind") == "value":
                add(type_model.get("type"), type_model.get("encoding", ""))
        return_type = operation.get("returns", {})
        if return_type.get("kind") == "value":
            add(return_type.get("type"), return_type.get("encoding", ""))
    return entries


def render_cpp(model: dict[str, Any]) -> str:
    api = model.get("api", "org.freecad.wasm.api@0")
    class_names = dict(classes(model))
    value_names = {full_name: name for full_name, name, _ in value_types(model)}
    lines = [
        "// Generated by generate_wasm_sdk.py. Do not edit.",
        "#pragma once",
        "",
        "#include <Wasm/Guest/WasmGuest.h>",
        "",
        "namespace FreeCAD::Wasm::Generated",
        "{",
        f'inline constexpr char ApiVersion[] = "{api}";',
        "using Handle = unsigned long long;",
        "",
    ]
    for _, name in class_names.items():
        lines.extend(
            [
                f"struct {name}",
                "{",
                "    Handle value = 0U;",
                "",
                "    constexpr explicit operator bool() const { return value != 0U; }",
                "};",
                "",
            ]
        )
    for _, name, encoding in value_types(model):
        if encoding != "vector3-f64":
            raise ValueError(f"unsupported C++ Wasm value encoding: {encoding}")
        lines.extend(
            [
                f"struct {name}",
                "{",
                "    double x = 0.0;",
                "    double y = 0.0;",
                "    double z = 0.0;",
                "};",
                "",
            ]
        )

    lines.extend(
        [
            "class Host",
            "{",
            "public:",
            "    Host() = default;",
            "",
            "    explicit Host(::Wasm::Guest::Client client)",
            "        : client_(client)",
            "    {",
            "    }",
            "",
            "    auto allocateResponse(unsigned int size) const",
            "    {",
            "        return client_.allocateResponse(size);",
            "    }",
            "",
        ]
    )
    for operation in model.get("operations", []):
        params = operation.get("params", [])
        return_type = operation.get("returns", {})
        method = operation.get("guest_method", operation.get("name", ""))
        name = operation.get("name", "operation")
        lines.append(f"    // {operation.get('wire_name', name)}")
        permission = operation.get("permission")
        if permission:
            lines.append(
                f'    inline static constexpr char {name}Permission[] = "{permission}";'
            )
        lines.append(
            f"    inline static constexpr unsigned char {name}Operation = "
            f"{int(operation.get('id', 0))}U;"
        )

        parameter_declarations = []
        call_arguments = []
        for parameter in params:
            parameter_type = parameter.get("type", {})
            kind = parameter_type.get("kind")
            if kind == "string":
                cpp_type = "const char*"
            elif kind == "float64":
                cpp_type = "double"
            elif kind == "bool":
                cpp_type = "bool"
            elif kind == "value":
                cpp_type = value_names[parameter_type["type"]]
            elif kind == "handle":
                full_name = parameter_type.get("type")
                cpp_type = "Handle" if full_name == "Wasm.Handle" else class_names[full_name]
            else:
                cpp_type = "Handle"
            parameter_name = parameter.get("name", "value")
            parameter_declarations.append(f"{cpp_type} {parameter_name}")
            if kind == "handle" and parameter_type.get("type") != "Wasm.Handle":
                call_arguments.append(f"{parameter_name}.value")
            elif kind == "value" and parameter_type.get("encoding") == "vector3-f64":
                call_arguments.append(
                    "::Wasm::Guest::Vector3{"
                    f"{parameter_name}.x, {parameter_name}.y, {parameter_name}.z}}"
                )
            else:
                call_arguments.append(parameter_name)

        if return_type.get("kind") == "string":
            parameter_declarations.extend(
                ["char* result", "unsigned int capacity", "unsigned int* length"]
            )
            lines.append(
                f"    bool {name}({', '.join(parameter_declarations)}) const"
            )
            lines.extend(
                [
                    "    {",
                    "        if (length == nullptr || (capacity != 0U && result == nullptr)) {",
                    "            return false;",
                    "        }",
                    f"        return client_.{method}({', '.join(call_arguments + ['result', 'capacity', 'length'])});",
                    "    }",
                    "",
                ]
            )
        elif return_type.get("kind") == "handle":
            result_type = return_type.get("type")
            result_cpp_type = "Handle" if result_type == "Wasm.Handle" else class_names[result_type]
            parameter_declarations.append(f"{result_cpp_type}* result")
            lines.append(
                f"    bool {name}({', '.join(parameter_declarations)}) const"
            )
            lines.extend(
                [
                    "    {",
                    "        if (result == nullptr) {",
                    "            return false;",
                    "        }",
                    "        ::Wasm::Guest::Handle raw = 0U;",
                    f"        if (!client_.{method}({', '.join(call_arguments + ['&raw'])})) {{",
                    "            return false;",
                    "        }",
                    "        result->value = raw;",
                    "        return true;",
                    "    }",
                    "",
                ]
            )
        elif return_type.get("kind") == "value":
            result_type = return_type.get("type")
            result_cpp_type = value_names[result_type]
            parameter_declarations.append(f"{result_cpp_type}* result")
            lines.append(
                f"    bool {name}({', '.join(parameter_declarations)}) const"
            )
            lines.extend(
                [
                    "    {",
                    "        if (result == nullptr) {",
                    "            return false;",
                    "        }",
                    "        ::Wasm::Guest::Vector3 raw;",
                    f"        if (!client_.{method}({', '.join(call_arguments + ['&raw'])})) {{",
                    "            return false;",
                    "        }",
                    "        result->x = raw.x;",
                    "        result->y = raw.y;",
                    "        result->z = raw.z;",
                    "        return true;",
                    "    }",
                    "",
                ]
            )
        elif return_type.get("kind") == "float64":
            parameter_declarations.append("double* result")
            lines.append(
                f"    bool {name}({', '.join(parameter_declarations)}) const"
            )
            lines.extend(
                [
                    "    {",
                    "        if (result == nullptr) {",
                    "            return false;",
                    "        }",
                    f"        return client_.{method}({', '.join(call_arguments + ['result'])});",
                    "    }",
                    "",
                ]
            )
        elif return_type.get("kind") == "bool":
            lines.append(
                f"    bool {name}({', '.join(parameter_declarations)}) const"
            )
            lines.extend(["    {"])
            if method == "release":
                lines.extend(
                    [
                        "#if defined(FREECAD_WASM_FREESTANDING)",
                        "        return client_.release(handle);",
                        "#else",
                        "        bool released = false;",
                        "        if (!client_.release(handle, &released)) {",
                        "            return false;",
                        "        }",
                        "        return released;",
                        "#endif",
                    ]
                )
            else:
                lines.extend(
                    [
                        "        bool value = false;",
                        f"        if (!client_.{method}({', '.join(call_arguments + ['&value'])})) {{",
                        "            return false;",
                        "        }",
                        "        return value;",
                    ]
                )
            lines.extend(["    }", ""])

    lines.extend(
        [
            "private:",
            "    ::Wasm::Guest::Client client_;",
            "};",
            "",
        ]
    )
    lines.extend(["}  // namespace FreeCAD::Wasm::Generated", ""])
    return "\n".join(lines)


def render_rust(model: dict[str, Any]) -> str:
    api = model.get("api", "org.freecad.wasm.api@0")
    class_names = dict(classes(model))
    value_names = {full_name: name for full_name, name, _ in value_types(model)}
    lines = [
        "// Generated by generate_wasm_sdk.py. Do not edit.",
        "",
        "use core::ptr;",
        "",
        "#[link(wasm_import_module = \"freecad\")]",
        "unsafe extern \"C\" {",
        "    fn freecad_alloc(size: u32) -> u32;",
        "    fn freecad_dispatch(request: *const u8, request_length: u32) -> u64;",
        "    fn freecad_release(response_address: u32);",
        "}",
        "",
        f'pub const API_VERSION: &str = "{api}";',
        "pub type Handle = u64;",
        "",
    ]
    for _, name, encoding in value_types(model):
        if encoding != "vector3-f64":
            raise ValueError(f"unsupported Rust Wasm value encoding: {encoding}")
        lines.extend(
            [
                "#[repr(C)]",
                "#[derive(Clone, Copy, Debug, PartialEq)]",
                f"pub struct {name}",
                "{",
                "    pub x: f64,",
                "    pub y: f64,",
                "    pub z: f64,",
                "}",
                "",
            ]
        )
    for _, name in classes(model):
        lines.extend(
            [
                "#[repr(transparent)]",
                "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
                f"pub struct {name}(pub Handle);",
                "",
            ]
        )
    operations = model.get("operations", [])
    if operations:
        lines.extend(["pub mod operations {", ""])
        for operation in operations:
            constant = re.sub(
                r"[^A-Za-z0-9]+",
                "_",
                re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", operation.get("name", "operation")),
            ).upper()
            lines.append(f"    pub const {constant}: u8 = {int(operation.get('id', 0))};")
            permission = operation.get("permission")
            if permission:
                lines.append(
                    f'    pub const {constant}_PERMISSION: &str = "{permission}";'
                )
        lines.extend(["", "}", ""])

    lines.extend(
        [
            "const REQUEST_HEADER_SIZE: usize = 12;",
            "const REQUEST_CAPACITY: usize = 512;",
            "const MAX_STRING_LENGTH: usize = 128;",
            "",
            "struct Request",
            "{",
            "    bytes: [u8; REQUEST_CAPACITY],",
            "    length: usize,",
            "}",
            "",
            "impl Request",
            "{",
            "    fn new(operation: u8, payload_length: usize) -> Option<Self>",
            "    {",
            "        if payload_length > REQUEST_CAPACITY - REQUEST_HEADER_SIZE",
            "            || payload_length > u32::MAX as usize",
            "        {",
            "            return None;",
            "        }",
            "        let mut request = Self {",
            "            bytes: [0; REQUEST_CAPACITY],",
            "            length: REQUEST_HEADER_SIZE,",
            "        };",
            "        request.bytes[0..4].copy_from_slice(b\"FCWA\");",
            "        request.bytes[4] = 1;",
            "        request.bytes[5] = operation;",
            "        request.bytes[8..12].copy_from_slice(&(payload_length as u32).to_le_bytes());",
            "        Some(request)",
            "    }",
            "",
            "    fn push_bytes(&mut self, bytes: &[u8]) -> Option<()>",
            "    {",
            "        let end = self.length.checked_add(bytes.len())?;",
            "        if end > REQUEST_CAPACITY {",
            "            return None;",
            "        }",
            "        self.bytes[self.length..end].copy_from_slice(bytes);",
            "        self.length = end;",
            "        Some(())",
            "    }",
            "",
            "    fn push_u8(&mut self, value: u8) -> Option<()>",
            "    {",
            "        self.push_bytes(&[value])",
            "    }",
            "",
            "    fn push_u32(&mut self, value: u32) -> Option<()>",
            "    {",
            "        self.push_bytes(&value.to_le_bytes())",
            "    }",
            "",
            "    fn push_u64(&mut self, value: u64) -> Option<()>",
            "    {",
            "        self.push_bytes(&value.to_le_bytes())",
            "    }",
            "",
            "    fn push_f64(&mut self, value: f64) -> Option<()>",
            "    {",
            "        self.push_u64(value.to_bits())",
            "    }",
            "",
            "    fn push_string(&mut self, value: &[u8]) -> Option<()>",
            "    {",
            "        if value.len() > MAX_STRING_LENGTH {",
            "            return None;",
            "        }",
            "        self.push_u32(value.len() as u32)?;",
            "        self.push_bytes(value)",
            "    }",
            "",
            "    fn push_vector(&mut self, value: FreeCADBaseVectorValue) -> Option<()>",
            "    {",
            "        self.push_f64(value.x)?;",
            "        self.push_f64(value.y)?;",
            "        self.push_f64(value.z)",
            "    }",
            "}",
            "",
            "#[derive(Clone, Copy, Debug, Default)]",
            "pub struct Client;",
            "",
            "impl Client",
            "{",
            "    pub const fn new() -> Self",
            "    {",
            "        Self",
            "    }",
            "",
            "    pub fn allocate_response(&self, size: u32) -> u32",
            "    {",
            "        unsafe { freecad_alloc(size) }",
            "    }",
            "",
            "    fn release_response(address: u32)",
            "    {",
            "        if address != 0 {",
            "            unsafe { freecad_release(address); }",
            "        }",
            "    }",
            "",
            "    fn call_handle(&self, request: &Request) -> Option<Handle>",
            "    {",
            "        let response = unsafe { freecad_dispatch(request.bytes.as_ptr(), request.length as u32) };",
            "        let address = response as u32;",
            "        let length = (response >> 32) as u32;",
            "        if address == 0 || length != 8 {",
            "            Self::release_response(address);",
            "            return None;",
            "        }",
            "        let mut bytes = [0u8; 8];",
            "        unsafe {",
            "            ptr::copy_nonoverlapping(address as *const u8, bytes.as_mut_ptr(), bytes.len());",
            "        }",
            "        Self::release_response(address);",
            "        let value = u64::from_le_bytes(bytes);",
            "        (value != 0).then_some(value)",
            "    }",
            "",
            "    fn call_value(&self, request: &Request) -> Option<FreeCADBaseVectorValue>",
            "    {",
            "        let response = unsafe { freecad_dispatch(request.bytes.as_ptr(), request.length as u32) };",
            "        let address = response as u32;",
            "        let length = (response >> 32) as u32;",
            "        if address == 0 || length != 24 {",
            "            Self::release_response(address);",
            "            return None;",
            "        }",
            "        let mut bytes = [0u8; 24];",
            "        unsafe {",
            "            ptr::copy_nonoverlapping(address as *const u8, bytes.as_mut_ptr(), bytes.len());",
            "        }",
            "        Self::release_response(address);",
            "        Some(FreeCADBaseVectorValue {",
            "            x: f64::from_bits(u64::from_le_bytes(bytes[0..8].try_into().ok()?)),",
            "            y: f64::from_bits(u64::from_le_bytes(bytes[8..16].try_into().ok()?)),",
            "            z: f64::from_bits(u64::from_le_bytes(bytes[16..24].try_into().ok()?)),",
            "        })",
            "    }",
            "",
            "    fn call_f64(&self, request: &Request) -> Option<f64>",
            "    {",
            "        let response = unsafe { freecad_dispatch(request.bytes.as_ptr(), request.length as u32) };",
            "        let address = response as u32;",
            "        let length = (response >> 32) as u32;",
            "        if address == 0 || length != 8 {",
            "            Self::release_response(address);",
            "            return None;",
            "        }",
            "        let mut bytes = [0u8; 8];",
            "        unsafe {",
            "            ptr::copy_nonoverlapping(address as *const u8, bytes.as_mut_ptr(), bytes.len());",
            "        }",
            "        Self::release_response(address);",
            "        Some(f64::from_bits(u64::from_le_bytes(bytes)))",
            "    }",
            "",
            "    fn call_bool(&self, request: &Request) -> Option<bool>",
            "    {",
            "        let response = unsafe { freecad_dispatch(request.bytes.as_ptr(), request.length as u32) };",
            "        let address = response as u32;",
            "        let length = (response >> 32) as u32;",
            "        if address == 0 || length != 1 {",
            "            Self::release_response(address);",
            "            return None;",
            "        }",
            "        let value = unsafe { *(address as *const u8) };",
            "        Self::release_response(address);",
            "        match value {",
            "            0 => Some(false),",
            "            1 => Some(true),",
            "            _ => None,",
            "        }",
            "    }",
            "",
            "    fn call_string(&self, request: &Request, output: &mut [u8]) -> Option<usize>",
            "    {",
            "        let response = unsafe { freecad_dispatch(request.bytes.as_ptr(), request.length as u32) };",
            "        let address = response as u32;",
            "        let length = (response >> 32) as u32;",
            "        if address == 0 || length < 4 {",
            "            Self::release_response(address);",
            "            return None;",
            "        }",
            "        let bytes = address as *const u8;",
            "        let mut value_length = 0u32;",
            "        unsafe {",
            "            for shift in 0..4 {",
            "                value_length |= (*bytes.add(shift) as u32) << (shift * 8);",
            "            }",
            "        }",
            "        if value_length != length - 4 || value_length as usize > output.len() {",
            "            Self::release_response(address);",
            "            return None;",
            "        }",
            "        unsafe {",
            "            ptr::copy_nonoverlapping(bytes.add(4), output.as_mut_ptr(), value_length as usize);",
            "        }",
            "        Self::release_response(address);",
            "        Some(value_length as usize)",
            "    }",
            "",
        ]
    )

    def rust_parameter_type(parameter: dict[str, Any]) -> str:
        parameter_type = parameter.get("type", {})
        kind = parameter_type.get("kind")
        if kind == "string":
            return "&[u8]"
        if kind == "float64":
            return "f64"
        if kind == "bool":
            return "bool"
        if kind == "value":
            return value_names[parameter_type["type"]]
        if kind == "handle":
            full_name = parameter_type.get("type")
            return "Handle" if full_name == "Wasm.Handle" else class_names[full_name]
        raise ValueError(f"unsupported Rust parameter type: {kind}")

    def payload_size_expression(params: list[dict[str, Any]]) -> str:
        sizes = []
        for parameter in params:
            parameter_type = parameter.get("type", {})
            kind = parameter_type.get("kind")
            if kind == "string":
                sizes.append(f"4usize + {parameter.get('name', 'value')}.len()")
            elif kind in {"float64", "handle"}:
                sizes.append("8usize")
            elif kind == "bool":
                sizes.append("1usize")
            elif kind == "value":
                sizes.append("24usize")
            else:
                raise ValueError(f"unsupported Rust payload type: {kind}")
        return " + ".join(sizes) if sizes else "0usize"

    def append_parameter(parameter: dict[str, Any], release_method: bool) -> list[str]:
        parameter_type = parameter.get("type", {})
        kind = parameter_type.get("kind")
        name = parameter.get("name", "value")
        failure = "return false;" if release_method else "return None;"
        if kind == "string":
            return [f"        request.push_string({name})?;"]
        if kind == "float64":
            return [
                f"        if request.push_f64({name}).is_none() {{ {failure} }}"
                if release_method
                else f"        request.push_f64({name})?;"
            ]
        if kind == "bool":
            return [
                f"        if request.push_u8({name} as u8).is_none() {{ {failure} }}"
                if release_method
                else f"        request.push_u8({name} as u8)?;"
            ]
        if kind == "value":
            if parameter_type.get("encoding") != "vector3-f64":
                raise ValueError(
                    f"unsupported Rust Wasm value encoding: {parameter_type.get('encoding')}"
                )
            return [
                f"        if request.push_vector({name}).is_none() {{ {failure} }}"
                if release_method
                else f"        request.push_vector({name})?;"
            ]
        if kind == "handle":
            value = name if parameter_type.get("type") == "Wasm.Handle" else f"{name}.0"
            return [
                f"        if request.push_u64({value}).is_none() {{ {failure} }}"
                if release_method
                else f"        request.push_u64({value})?;"
            ]
        raise ValueError(f"unsupported Rust parameter type: {kind}")

    for operation in operations:
        name = operation.get("name", "operation")
        method = rust_method_name(name)
        params = operation.get("params", [])
        return_type = operation.get("returns", {})
        return_kind = return_type.get("kind")
        if return_kind == "handle":
            result_type = return_type.get("type")
            result_name = "Handle" if result_type == "Wasm.Handle" else class_names[result_type]
            result_signature = f"Option<{result_name}>"
        elif return_kind == "value":
            result_signature = "Option<{}>".format(value_names[return_type["type"]])
        elif return_kind == "float64":
            result_signature = "Option<f64>"
        elif return_kind == "string":
            result_signature = "Option<usize>"
        elif return_kind == "bool":
            result_signature = "bool" if name == "release" else "Option<bool>"
        else:
            raise ValueError(f"unsupported Rust return type: {return_kind}")
        declarations = [
            f"{parameter.get('name', 'value')}: {rust_parameter_type(parameter)}"
            for parameter in params
        ]
        if return_kind == "string":
            declarations.append("output: &mut [u8]")
        signature = ", ".join(["&self", *declarations])
        lines.append(f"    pub fn {method}({signature}) -> {result_signature}")
        lines.extend(["    {"])
        if any(parameter.get("type", {}).get("kind") == "string" for parameter in params):
            for parameter in params:
                if parameter.get("type", {}).get("kind") == "string":
                    lines.append(
                        f"        if {parameter.get('name', 'value')}.len() > MAX_STRING_LENGTH {{"
                    )
                    lines.append("            return " + ("false" if name == "release" else "None") + ";")
                    lines.append("        }")
        operation_constant = re.sub(
            r"[^A-Za-z0-9]+",
            "_",
            re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name),
        ).upper()
        if return_kind == "bool" and name == "release":
            lines.extend(
                [
                    f"        let mut request = match Request::new(operations::{operation_constant}, "
                    f"{payload_size_expression(params)}) {{",
                    "            Some(request) => request,",
                    "            None => return false,",
                    "        };",
                ]
            )
        else:
            lines.append(
                f"        let mut request = Request::new(operations::{operation_constant}, "
                f"{payload_size_expression(params)})?;"
            )
        for parameter in params:
            lines.extend(append_parameter(parameter, return_kind == "bool" and name == "release"))
        if return_kind == "handle":
            lines.extend(
                [
                    f"        self.call_handle(&request).map({result_name})",
                    "    }",
                    "",
                ]
            )
        elif return_kind == "value":
            lines.extend(["        self.call_value(&request)", "    }", ""])
        elif return_kind == "float64":
            lines.extend(["        self.call_f64(&request)", "    }", ""])
        elif return_kind == "string":
            lines.extend(["        self.call_string(&request, output)", "    }", ""])
        elif return_kind == "bool" and name == "release":
            lines.extend(
                [
                    "        let response = unsafe { freecad_dispatch(request.bytes.as_ptr(), request.length as u32) };",
                    "        let address = response as u32;",
                    "        let length = (response >> 32) as u32;",
                    "        Self::release_response(address);",
                    "        address == 0 && length == 0",
                    "    }",
                    "",
                ]
            )
        elif return_kind == "bool":
            lines.extend(["        self.call_bool(&request)", "    }", ""])
        else:
            raise ValueError(f"unsupported Rust return type: {return_type.get('kind')}")

    lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--api-json", required=True, type=Path)
    parser.add_argument("--cpp-output", required=True, type=Path)
    parser.add_argument("--rust-output", required=True, type=Path)
    args = parser.parse_args()

    model = json.loads(args.api_json.read_text(encoding="utf-8"))
    args.cpp_output.parent.mkdir(parents=True, exist_ok=True)
    args.rust_output.parent.mkdir(parents=True, exist_ok=True)
    args.cpp_output.write_text(render_cpp(model), encoding="utf-8")
    args.rust_output.write_text(render_rust(model), encoding="utf-8")


if __name__ == "__main__":
    main()
