from typing import Sequence, overload

class Vector:
    def __add__(self, vector2: "Vector", /) -> "Vector": ...
    def __sub__(self, vector2: "Vector", /) -> "Vector": ...
    @overload
    def __mul__(self, factor: float, /) -> "Vector": ...
    @overload
    def __mul__(self, vector2: "Vector", /) -> float: ...
    def __rmul__(self, factor: float, /) -> "Vector": ...
    def __truediv__(self, factor: float, /) -> "Vector": ...

class Placement:
    Rotation: "FreeCAD.Base.Rotation" = ...
    Matrix: "FreeCAD.Base.Matrix" = ...

    @overload
    def __init__(self, matrix: "FreeCAD.Base.Matrix") -> None: ...
    @overload
    def __init__(self, base: Vector, rotation: "FreeCAD.Base.Rotation") -> None: ...
    @overload
    def __init__(
        self,
        base: Vector,
        rotation: "FreeCAD.Base.Rotation",
        center: Vector,
    ) -> None: ...
    @overload
    def __mul__(self, vector: Vector, /) -> Vector: ...
    @overload
    def __mul__(self, rotation: "FreeCAD.Base.Rotation", /) -> "Placement": ...
    @overload
    def __mul__(self, matrix: "FreeCAD.Base.Matrix", /) -> "FreeCAD.Base.Matrix": ...
    @overload
    def __mul__(self, placement: "Placement", /) -> "Placement": ...
    def toMatrix(self) -> "FreeCAD.Base.Matrix": ...
