# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations
from typing import overload

@overload
def listSchemas() -> tuple[str, ...]: ...
@overload
def listSchemas(index: int, /) -> str: ...
@overload
def toNumber(value: Quantity, format: _NumberFormat = ..., decimals: int = ..., /) -> str: ...
@overload
def toNumber(value: float, format: _NumberFormat = ..., decimals: int = ..., /) -> str: ...
def parseQuantity(expression: str, /) -> Quantity: ...
def getSchema() -> int: ...
def setSchema(index: int, /) -> None: ...
def schemaTranslate(quantity: Quantity, schema: int, /) -> tuple[str, float, str]: ...
