# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

def translate(
    context: str, sourcetext: str, disambiguation: str | None = None, n: int = -1, /
) -> str: ...
def QT_TRANSLATE_NOOP(context: object, sourcetext: _T, /) -> _T: ...
def QT_TRANSLATE_NOOP3(context: object, sourcetext: _T, disambiguation: object, /) -> _T: ...
def QT_TRANSLATE_NOOP_UTF8(context: object, sourcetext: _T, /) -> _T: ...
def QT_TR_NOOP(sourcetext: _T, /) -> _T: ...
def QT_TR_NOOP_UTF8(sourcetext: _T, /) -> _T: ...
def installTranslator(filename: str, /) -> bool: ...
def removeTranslators() -> bool: ...
