# SPDX-License-Identifier: LGPL-2.1-or-later

from __future__ import annotations

from typing import Literal, TypeAlias

_MessageType: TypeAlias = Literal["Log", "Wrn", "Msg", "Err", "Critical", "Notification"]

def PrintMessage(obj: object, output: object = ..., /) -> None: ...
def PrintLog(obj: object, output: object = ..., /) -> None: ...
def PrintError(obj: object, output: object = ..., /) -> None: ...
def PrintDeveloperError(obj: object, output: object = ..., /) -> None: ...
def PrintUserError(obj: object, output: object = ..., /) -> None: ...
def PrintTranslatedUserError(obj: object, output: object = ..., /) -> None: ...
def PrintWarning(obj: object, output: object = ..., /) -> None: ...
def PrintDeveloperWarning(obj: object, output: object = ..., /) -> None: ...
def PrintUserWarning(obj: object, output: object = ..., /) -> None: ...
def PrintTranslatedUserWarning(obj: object, output: object = ..., /) -> None: ...
def PrintCritical(obj: object, output: object = ..., /) -> None: ...
def PrintNotification(obj: object, output: object = ..., /) -> None: ...
def PrintTranslatedNotification(obj: object, output: object = ..., /) -> None: ...
def SetStatus(observer: str, type: _MessageType, status: bool, /) -> None: ...
def GetStatus(observer: str, type: _MessageType, /) -> bool | None: ...
def GetObservers() -> list[str]: ...
