// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#include <emscripten/bind.h>
#include <Base/Vector3D.h>

extern "C" void embind_init_base_vector()
{
    emscripten::class_<Base::Vector3d>("Vector")
        .property("x", &Base::Vector3d::x)
        .property("y", &Base::Vector3d::y)
        .property("z", &Base::Vector3d::z)
        .property("Length", &Base::Vector3d::Length)
        .property("Sqr", &Base::Vector3d::Sqr)
        .property("IsNull", &Base::Vector3d::IsNull)
        .constructor<double, double, double>()
        #if 0
        .function("operator-", &Base::Vector3d::operator-)
        .function("operator*", &Base::Vector3d::operator*)
        .function("operator/", &Base::Vector3d::operator/)
        .function("operator*=", &Base::Vector3d::operator*=)
        .function("operator/=", &Base::Vector3d::operator/=)
        #endif
        .function("ScaleX", &Base::Vector3d::ScaleX)
        .function("ScaleY", &Base::Vector3d::ScaleY)
        .function("ScaleZ", &Base::Vector3d::ScaleZ)
        .function("Scale", &Base::Vector3d::Scale)
        .function("MoveX", &Base::Vector3d::MoveX)
        .function("MoveY", &Base::Vector3d::MoveY)
        .function("MoveZ", &Base::Vector3d::MoveZ)
        .function("Move", &Base::Vector3d::Move)
        .function("RotateX", &Base::Vector3d::RotateX)
        .function("RotateY", &Base::Vector3d::RotateY)
        .function("RotateZ", &Base::Vector3d::RotateZ)
        .function("Set", &Base::Vector3d::Set)
        .function("Normalize", &Base::Vector3d::Normalize)
        .function("GetAngle", &Base::Vector3d::GetAngle)
        .function("TransformToCoordinateSystem", &Base::Vector3d::TransformToCoordinateSystem)
        .function("IsEqual", &Base::Vector3d::IsEqual)
        .function("ProjectToLine", &Base::Vector3d::ProjectToLine)
        .function("Perpendicular", &Base::Vector3d::Perpendicular)
        .function("DistanceToPlane", &Base::Vector3d::DistanceToPlane)
        .function("DistanceToLine", &Base::Vector3d::DistanceToLine)
        .function("DistanceToLineSegment", &Base::Vector3d::DistanceToLineSegment)
        ;
}
